### ISSUE TITLE
Dell H200 - megacli nor storcli shows any adapters

### ISSUE THREAD

**Issue by cake99** [astersmith/esos#101]
[root@san2 ~]# find /opt
/opt
/opt/lib
/opt/lib/libstorelibir-2.so.14
/opt/lib/libstorelibir-2.so.14.07-0
/opt/bin
/opt/sbin
/opt/sbin/MegaCli64
/opt/sbin/storcli64
[root@san2 ~]# /opt/sbin/storcli64 show all
Status Code = 0
Status = Success
Description = None

Number of Controllers = 0
Host Name = san2.home
Operating System  = Linux3.14.36-esos.prod

[root@san2 ~]# /opt/sbin/MegaCli64 -CfgDsply -aALL

Exit Code: 0x00

This is the first time I try with this card (Dell H200).  Everything works beside the management of the raid card.

**Comment by msmith626** [comment]
Hi,

It doesn't appear that RAID controller is a MegaRAID variety... I believe its more like the software/integrated type controller. For now, you'll need to use the BIOS utility to configure volumes. Or you could pass the disks through and use Linux software RAID (md).


--Marc
