### ISSUE TITLE
re-creating scst.conf after a wipe

### ISSUE THREAD

**Issue by cake99** [astersmith/esos#104]
It's not a big deal, but I'm wondering how to re-create a scst.conf after a clear command.
I did it twice mainly fo rtesting and then I'm left with an empty scst.conf file. So I load manually the module (modprobe scst), then I can go into the TUI.  But there I don't see any target's or anything else.

How can I revert to initial settings without re-creating another usb key?

Thanks a lot!

**Comment by msmith626** [comment]
Not sure I totally understand the question... you want to revert to a clean/empty SCST state? Like no SCST configuration? If so, you could do this (via shell):
/etc/rc.d/rc.scst stop
mv /etc/scst.conf /etc/scst.conf.orig
/etc/rc.d/rc.scst start

If you want to just maintain different SCST configurations, use similar commands above and keep different /etc/scst.conf configuration files (eg, /etc/scst.conf.1 /etc/scst.conf.2).


--Marc

**Comment by cake99** [comment]
If I clear the config, the TUI shows me at the target tab "no target found"
or something similar.

Is there an easy way to re-create the target section, without groups in it?
Basically starting like I had a fresh install.

**Comment by msmith626** [comment]
How are you "clearing the config"? Are you using the scstadmin tool, or manipulating the file? Or something else?

What kind of targets? iSCSI?

You could have a minimal setup with your targets, sync the config, then: cp /etc/scst.conf /etc/scst.conf.base

When ever you want to start with the "base" configuration again with only your targets cp -f /etc/scst.conf.base /etc/scst.conf && scstadmin -force -config /etc/scst.conf
Or some other variation of the above.


--Marc

**Comment by msmith626** [comment]
I'm going to assume your question has been answered; if you have any additional comments for this topic, please share them on the esos-users Google Group as other users may have had the same question / solution.

--Marc

**Comment by cake99** [comment]
This has been totally answered, thanks a lot.
Le Sun, Apr 5, 2015 à 11:20 PM, Marc A. Smith <notifications@github.com> a
écrit :
