### ISSUE TITLE
ESX datastore and ESOS SAN - special configuration?

### ISSUE THREAD

**Issue by cake99** [astersmith/esos#106]
I'm having a hard time setting up my two ESOS SAN's and ESX boxes.
It looks like having one datastore from one ESOS shared to two ESX server is ok.  Then I add a second datastore from another ESOS to both ESX server and problems start happenning.
I can't finish creating the datastore, it's locked in "loading...".

I also noted that each SAN need to set different lun number, if not the esx will think it's the same disk.  Am I missing something else?

![image](https://cloud.githubusercontent.com/assets/11451552/6966277/caade1fc-d925-11e4-89ae-bc2697862113.png)

**Comment by cake99** [comment]
I have to add that everything else keeps working.  My VM are still having good performance while the management GUI has trouble loading the disks.

**Comment by msmith626** [comment]
Hi,

These types of questions really belong on the "esos-users" Google Group. Please post to the list with your SCST configuration files, at least your kern.log files from ESOS side and vmkernel.log files from ESXi hosts. Be prepared to describe the details of your SAN configuration as well.


--Marc
