### ISSUE TITLE
Presentation of SRP target prevents vsphere multipathing?

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#112]
So at the moment, I have no IB switch.  For the moment, the main vsphere host connects directly to the esos server.  The backup vsphere host connects to the same LUN(s) using iSCSI.  I had thought to connect the main vsphere host using iSCSI also (with the SRP target being preferred in vsphere path management).  It will NOT present the LUN for storage management.  After much fiddling around, I discovered it is because the SRP target is flagged with VMW_SATP_LOCAL, when it should be VMW_SATP_DEFAULT_AA (or maybe VMW_SATP_DEFAULT_ALUA?)  LOCAL is not capable of multipathing, so it hides it.  This is not a show stopper, but I had thought to have a little 'belt and suspenders' in case the IB link went down.  I'm suspecting something SCST-related, since when I was playing with various solaris-type distros with SRP target, this all 'just worked'.

**Comment by msmith626** [comment]
Hi Dan,

I'm not sure I follow the question... when you say "It will NOT present the
LUN for storage management" are you referring to the ESOS box, or vSphere?
The SRP target "flagged with VMW_SATP_LOCAL" is all vSphere and nothing to
do with ESOS/SCST... ESXi uses NMP SATP claim rules to select the path
policy / path module in ESXi -- these rules control which is selected by
default. You can adjust the claim rules in vSphere.

If I remember correctly, by default, ESXi uses VMW_SATP_DEFAULT_ALUA if it
detects an ALUA configuration (target groups), and some other one if not.
Again, these are all vSphere specific things and nothing really to do with
ESOS/SCST... its all configuration. Other Solaris-type distros with SRP
targets might have evaluated to using a different plugin based on the claim
rules in ESXi.


--Marc

**Comment by dswartz** [comment]
On 2015-04-27 17:00, Marc A. Smith wrote:
> Hi Dan,
> 
>  I'm not sure I follow the question... when you say "It will NOT
> present the
>  LUN for storage management" are you referring to the ESOS box, or
> vSphere?
>  The SRP target "flagged with VMW_SATP_LOCAL" is all vSphere and
> nothing to
>  do with ESOS/SCST... ESXi uses NMP SATP claim rules to select the
> path
>  policy / path module in ESXi -- these rules control which is selected
> by
>  default. You can adjust the claim rules in vSphere.
> 
>  If I remember correctly, by default, ESXi uses VMW_SATP_DEFAULT_ALUA
> if it
>  detects an ALUA configuration (target groups), and some other one if
> not.
>  Again, these are all vSphere specific things and nothing really to do
> with
>  ESOS/SCST... its all configuration. Other Solaris-type distros with
> SRP
>  targets might have evaluated to using a different plugin based on the
> claim
>  rules in ESXi.

Sorry, vsphere.  What I meant was: it must be something SCST is doing 
differently than opensolaris, since vsphere is behaving differently.  
Yeah, I saw a couple of articles about adjusting all this in vsphere at 
the CLI and was thinking 'whoa!!!' :)  I found all kinds of stuff about 
changing the pathing preference, but that doesn't help me - I would have 
needed something that tells vsphere 'this is NOT local!'  I do note the 
LUN is displayed in vsphere as 'parallel scsi'?

**Comment by msmith626** [comment]
You should be able to change VMW_SATP_LOCAL to one of the other SATP
plugins using the claim rules. What device handler are you using with SCST?

**Comment by dswartz** [comment]
On 2015-04-27 18:22, Marc A. Smith wrote:
> You should be able to change VMW_SATP_LOCAL to one of the other SATP
>  plugins using the claim rules. What device handler are you using with
> SCST?

vdisk_blockio.  i think i screwed up though.  previously i had been 
using vdisk_fileio with block_device underlying.  i'm going to change 
that and see if it helps...  i assume the other host sees it as 
multipath capable since the transport is iSCSI.  somehow vsphere is 
confused?

**Comment by msmith626** [comment]
I'm honestly not sure, and still not sure I understand your setup. =)

**Comment by dswartz** [comment]
On 2015-04-27 22:31, Marc A. Smith wrote:
> I'm honestly not sure, and still not sure I understand your setup. =)

I have a raid10 on ESOS.  I have it exported via the srp target.  
vsphere1 (with the IB HCA) has a VMFS datastore on that LUN.  vsphere2 
(no HCA) mounts the LUN via iSCSI.  Works fine.  I also want vsphere1 to 
mount the LUN with iSCSI and set the SRP target as preferred.  But that 
doesn't work with SCST because the SRP LUN is showing as VMW_SATP_LOCAL. 
  Does that make more sense?  (and somehow solaris must have been 
presenting things differently, because it 'just worked'...)

**Comment by msmith626** [comment]
Yeah, so you're trying to use one volume across two different path
"mediums" (one SRP, one iSCSI). I thought we had talked about this earlier,
and I wasn't sure if it was even possible in vSphere... I could have swore
you said it was working, anyways...

So if the issue truly is with the plugin in vSphere, you should be able to
change it. This article sounds like it might get you where you need to be:
http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2041905


--Marc

**Comment by dswartz** [comment]
On 2015-04-27 22:45, Marc A. Smith wrote:
> Yeah, so you're trying to use one volume across two different path
>  "mediums" (one SRP, one iSCSI). I thought we had talked about this
> earlier,
>  and I wasn't sure if it was even possible in vSphere... I could have
> swore
>  you said it was working, anyways...
> 
>  So if the issue truly is with the plugin in vSphere, you should be
> able to
>  change it. This article sounds like it might get you where you need
> to be:
> 
> http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2041905

Yes.  With Solaris 11.2, when I present a LUN via SRP, it is NOT 
VMW_SATP_LOCAL, so the multipathing worked.  It isn't critical, just my 
OCD kicking in :)  I'll check out that article, thanks...

**Comment by dswartz** [comment]
I'm starting to wonder if one of the IB cards I got on ebay is flaky.  I 
was looking at the logs from when I had opensolaris running, and I 
noticed that consistently on boot, initializing the IB card got some 
weird error, but I ignored that, since it seemed to be working okay.  
Wondering if the linux driver isn't so okay...  I do have one spare 
card, but it's a PITA to figure out which is flaky, since I will have to 
swap the spare with the esos card and if that doesn't work, shut down 
the vsphere box and swap with that one.  Sigh...  BTW, the 10 second 
sleep trick didn't help.  I tried rebooting a good 6-7 times and it 
never sees the SRP target.  I'm going to try one more time with doing a 
power cycle (maybe the card is not warm initializing right...)

**Comment by dswartz** [comment]
Interesting.  So I had to reboot this morning for other reasons.  While it was off, I pulled the IB card in the ESOS box and replaced it with a spare.  I then rebooted, and... SRP target present?  Just to be paranoid, I did a warm reboot on the ESOS box.  'Target fe80:0000:0000 ....' not present.  Powered box off and back on.  No difference.  It's like it only sees it the very first time.  Only wait, I enabled IPOIB and rebooted, and now the SRP target is there.  This is beyond frustrating.  I think I'm about ready to call an end to the IB experiment and shell out for a couple of 10gbe nics :(

**Comment by dswartz** [comment]
Almost forgot: changing the SRP target device to vdisk_fileio from vdisk_blockio caused the SATP type in vsphere to change to VMW_SATP_DEFAULT_AA, so multipathing works now.  Won't help if the SRP target keeps disappearing on boot.  I'm going to try a couple of reboots to see...

**Comment by dswartz** [comment]
Okay, it is NOT SRP-specific.  I changed the config to set up IPOIB, and did perf testing and got decent (2-3 times better than gig-e).  So I disabled the SRP target and rebooted.  And no SRP target, but also, no ib0 interface.  Something is not being initialized right, and I don't know what.  I tried the sleep between early and late init and it didn't help.  So, I give up.  10-gig for me, I guess.  I absolutely cannot have the system go down (like it did last night due to a power failure in our town), and have no storage.  Sucks, but no real choice here...

**Comment by msmith626** [comment]
I honestly haven't heard of anyone else having this type of ESOS or even
with SCST on a vanilla Linux distro. One last ditch effort: When it boots
up and the SCST target interfaces don't appear, try these (or different
combinations of them):
- Run this to stop SCST and start it: /etc/rc.d/rc.scst stop &&
/etc/rc.d/rc.scst start
- Run this to unload IB modules and re-load them: /etc/rc.d/rc.openibd stop
&& /etc/rc.d/rc.openibd start

See what it does after each, if you have to unload everything... the goal
is to try and reproduce this (or fix it) without a reboot... if stopping
SCST and unloading the IB modules has no effect, I'd say its definitely
something hardware related.


--Marc

**Comment by dswartz** [comment]
Okay, will do.  I tried a quick install of ubuntu 14.04 just to see if it had the issue.  I did notice this on boot:

[    2.035324] mlx4_core: Mellanox ConnectX core driver v2.2-1 (Feb, 2014)
[    2.035331] mlx4_core: Initializing 0000:02:00.0
[    2.035463] mlx4_core 0000:02:00.0: enabling device (0000 -> 0002)
[    4.404678] mlx4_core 0000:02:00.0: PCIe link speed is 5.0GT/s, device supports 5.0GT/s
[    4.425710] mlx4_core 0000:02:00.0: PCIe link width is x8, device supports x8
[    4.437560] mlx4_core 0000:02:00.0: irq 57 for MSI/MSI-X
[    4.437564] mlx4_core 0000:02:00.0: irq 58 for MSI/MSI-X
[    4.437566] mlx4_core 0000:02:00.0: irq 59 for MSI/MSI-X
[    4.437569] mlx4_core 0000:02:00.0: irq 60 for MSI/MSI-X
[    4.437572] mlx4_core 0000:02:00.0: irq 61 for MSI/MSI-X
[    4.437575] mlx4_core 0000:02:00.0: irq 62 for MSI/MSI-X
[    4.437578] mlx4_core 0000:02:00.0: irq 63 for MSI/MSI-X
[    4.437581] mlx4_core 0000:02:00.0: irq 64 for MSI/MSI-X
[    4.437585] mlx4_core 0000:02:00.0: irq 65 for MSI/MSI-X
[    4.437588] mlx4_core 0000:02:00.0: irq 66 for MSI/MSI-X
[    4.437590] mlx4_core 0000:02:00.0: irq 67 for MSI/MSI-X
[    4.437593] mlx4_core 0000:02:00.0: irq 68 for MSI/MSI-X
[    4.437595] mlx4_core 0000:02:00.0: irq 69 for MSI/MSI-X
[    4.460751] mlx4_core 0000:02:00.0: command 0xc failed: fw status = 0x40
[    4.489621] mlx4_en: Mellanox ConnectX HCA Ethernet driver v2.2-1 (Feb 2014)
[   17.213829] <mlx4_ib> mlx4_ib_add: mlx4_ib: Mellanox ConnectX InfiniBand driver v2.2-1 (Feb 2014)

But everything comes up, so I'm guessing it's harmless?  Anyway, seems to me there may be an issue with FW revision or something throwing off the timing.  The first time boot introduces a significant delay (no?) while ESOS configures everything.  I'm wondering if the card has some kind of significant delay on start.  If I unload and reload the IB drivers, where should I be looking for log messages (if any)?

**Comment by msmith626** [comment]
That 'command 0xc failed' message may be harmless, I'm honestly not sure.
Look in /var/log/kern.log for messages when loading/unloading IB modules.

**Comment by dswartz** [comment]
Should anything be getting logged other than errors?

**Comment by msmith626** [comment]
Well, I would assume normal "information" messages about the
modules/devices being loaded. What kind of error messages are you getting?

**Comment by dswartz** [comment]
Sorry if I was unclear.  I haven't yet done your experiment(s).  I was more curious what, if any, non-error messages I might expect to see from the openibd drivers when they are loading (enumerating devices, creating ib nics, etc...)

**Comment by msmith626** [comment]
I guess something different than what you seen on the first boot where it
didn't work. =)

Just looking to see if the experiment makes it work, or doesn't really, and
then we can go from there.

**Comment by dswartz** [comment]
Got it...

**Comment by dswartz** [comment]
Well, I give up.  I've tried a zillion combos of things and have no root cause.  I thought it *might* be related to timezone or something, since I actually got 4 reboots in a row to work.  Then I rebooted again, and now it's back to failing for N times in a row.  I appreciate the work you've put in, but it isn't my HW - I've used the same cards with 4 different distros of solaris and linux and they just work.  It's got to be something funky with the sync to ramdisk timing or something.  Once it's borked, I can unload and reload the drivers a zillion times and it never helps.

**Comment by msmith626** [comment]
Eh, lots of other people use ESOS with IB hardware for SRP targets without
this issue... at least none that I've heard of for the last 3+ years. We're
really not doing anything special, its just Linux. I don't think the root
tmpfs file system would have anything to do with it, as both the IB stack
and SCST are all kernel modules.

Maybe its some issue with the Linux kernel version we're using... we use
the vanilla IB stack, no OFED. If I hear of anything, I'll let you know.


--Marc

**Comment by dswartz** [comment]
Marc, it isn't just SRP.  When this happens, /sys/class/infiniband is empty and no ib0 interface...

**Comment by msmith626** [comment]
Makes sense, since unloading/loading the IB modules and unloading/loading
SCST modules doesn't ever resolve your issue... its something outside of
SCST... the hardware is never initialized/available with the Linux kernel.

**Comment by dswartz** [comment]
Quick question: if I get an intel (say 520) 10gb card, that should just look like a NIC, right?  No IB fabric, SM involvement, etc?

**Comment by msmith626** [comment]
Look like a NIC? Isn't an Intel 520 an Ethernet NIC?

--Marc

**Comment by dswartz** [comment]
On 2015-04-30 21:11, Marc A. Smith wrote:
> Look like a NIC? Isn't an Intel 520 an Ethernet NIC?

Sorry for being unclear.  From my experience with the Mellanox HCA, it 
can be made to look like an IB device or a 10gb enet device.  The latter 
requires loading at least mlxen driver (IIRC).  So the IB stuff does 
come into play.  Whatever weirdness was afflicting my experiments with 
IB and this supermicro motherboard + Mellanox HCA, I'd rather not run 
with scissors again :)  So if it's a NIC with vanilla intel drivers, I 
*should* be safe, I would think?

**Comment by msmith626** [comment]
Gotcha; as far as I know, the Intel 520 is just a normal Ethernet NIC... no
IB personality... uses the standard Intel driver.

Do you know what (if any) firmware that Mellanox HCA uses? Is it loaded at
run-time (eg, when the module loads)? Or just uses built-in firmware?


--Marc

**Comment by dswartz** [comment]
No idea - as far as I know, it's onboard, cuz I've read articles about how to flash it if needed.  I happened to see another question someone raised earlier this year about iSER support.  That would be nice if&when SCST devs get around to it.

**Comment by dswartz** [comment]
I think this issue can be put to bed now - whatever the oddity is, it's clearly not a general one...
