### ISSUE TITLE
Feature request - update resource agents and btier

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#114]
Hi, would you update resource agents to latest which include clvm ra? Also, would you update btier to latest stable version 1.3.11?

I try update myself, but building fail. I try on centos 6.2. I figure out, that I need additional package installed "openais", but build still fail :(, probably something with btier...

**Comment by msmith626** [comment]
Yes, I can get to this tomorrow, or possibly later this evening.

--Marc

**Comment by msmith626** [comment]
I start this and will have it committed and pushed tomorrow morning.

--Marc

**Comment by msmith626** [comment]
This has been pushed and it builds fine on my development machine. The
Buildbot should pickup the change within the next 10 minutes and have the
new build posted in the downloads area (master branch) in about an hour.

--Marc
