### ISSUE TITLE
Update health check script to support ZFS

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#117]
I am modifying the health check script to check any ZFS pools and issue a warning if one or more are degraded or unavailable.  I will open a pull request when done.

**Comment by msmith626** [comment]
Does ZFS have its own set of monitoring tools/daemons?

--Marc

**Comment by dswartz** [comment]
On 2015-05-07 22:27, Marc A. Smith wrote:
> Does ZFS have its own set of monitoring tools/daemons?

Not really.  You generally use icinga/nagios or something to query for 
pool health.

**Comment by msmith626** [comment]
Okay, figured it was worth asking. Yeah, that sounds like a nice
addition... you could check /proc for the zfs module to see if it should
perform the checks (or whatever method you prefer). Thanks for the
contribution.

--Marc

**Comment by dswartz** [comment]
I'm still working on this.  I would hold off on trying to actually use ZFS at this point.  It seems like the mass of commits/fixes/enhancements to generate the 0.6.4 RC have introduced some serious stability issues...

**Comment by dswartz** [comment]
Pull Request 127 opened.  Note that I did not have an esos install with zfs support to hand, so I did the coding and testing on a centos VM, running the changed health script (ignoring irrelevant errors).  I am not 100% sure of the zpool executable path (I used the one centos distro had - you might need to change it.)  Output looks like this:

pool foo is offline or degraded!

**Comment by dswartz** [comment]
Marc, have you had a chance to look at this PR?

**Comment by msmith626** [comment]
I've glanced at it, and I believe the only change I noticed that I need to
make is to have it check that ZFS is enabled on the system, otherwise it
shouldn't perform the check at all... I was thinking about checking if the
zfs module is loaded, but I need to load up the ZFS version of ESOS to test
this first. I'll try to get to it this evening. Thank you for the addition.

--Marc

**Comment by dswartz** [comment]
So I'm on the most recent ZFS snapshot you sent me.  8 disks in raid10.  Exporting zvol to vsphere and veeam via vanilla 10gbe iSCSI.  crystaldiskmark 600MB/sec read and write in async mode.  In sync mode, even with very good SSD for SLOG, getting 160MB/sec on writes.  My next step is to invest in a decent raid controller that supports write-back caching in jbod/single-disk mode, so I can pass all the disks to ESOS and still get good write performance.  Two possibilities:

a) Don't use an SLOG at all - set all 8 data disks in write-back mode and rely on the 1GB or so of write-back cache to mitigate ZIL thrashing.
b) Use the same slog - leave the 8 data disks uncached (at raid controller level), but set the SLOG SSD in single-disk mode with write-back cache enabled.

I need to find a decent deal on ebay first :)

**Comment by dswartz** [comment]
Aside from the bit-rot protection, here is another reason to love ZFS.  So I have 8 VMs in a vsphere datastore on an ESOS ZFS software raid10.  Check this out:

tank/vsphere  compressratio  1.99x

this is with lz4 compression (very fast and efficient).  what the above means: i am using 1/2 the storage that vsphere thinks i am using.  Confirm this by doing 'zfs list':

tank/vsphere   164G  2.39T   164G  /tank/vsphere

yet according to the vsphere client, the datastore is 300GB.  Sweet!

**Comment by msmith626** [comment]
Nice!

**Comment by msmith626** [comment]
Completed, thanks for your work on this.

--Marc
