### ISSUE TITLE
Feature request - update dlm, corosync, pacemaker, crmsh

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#120]
Hi, I found that DLM version 4.0.2 fixed some issues with fencing, corosync 2.3.4, pacemaker 1.1.12 and crmsh 1.2.6/2.1 release with many fixes and improvements.

**Comment by msmith626** [comment]
Getting to this tonight... do you know if its safe/supported to go to crmsh
2.1 (instead of 1.2.6)? I haven't looked into it yet.

--Marc

**Comment by feldsam** [comment]
Hi, I think that it's ok when we have latest pacemaker

**Comment by msmith626** [comment]
Sorry this took so long, but its now complete... committed/pushed to master and new image is now available. One caveat: I just merged in udev support into master as well, so there may potentially be other issues -- I know of a couple minor cosmetic ones that I'm working on already.

--Marc

**Comment by feldsam** [comment]
Hello, thank You! Would you post somewhere your building env? I wrote befere, that I try to build esos but I was unsuccess.

**Comment by msmith626** [comment]
I can send you a VMware ovf of the buildbot host. Would that work?

**Comment by msmith626** [comment]
Let me know if the OVF will work. I had a chance to test the latest build
tonight and crm[sh] doesn't run... looks like it uses "lxml" from Python so
I need to look and see why this module isn't being built. I'll take a look
at it in the morning.

--Marc

**Comment by feldsam** [comment]
Hi, I don't test it yet.

**Comment by feldsam** [comment]
Hi, I try latest build today and I got same error:

    No module named lxml
    No module named modules

**Comment by msmith626** [comment]
Working on it now... should have it completed later this morning or early
afternoon.

--Marc

**Comment by msmith626** [comment]
I just pushed this and the Buildbot should have the new image posted in
about an hour. I tested 'crm' and it loads fine now with lxml.

--Marc
