### ISSUE TITLE
Connectx-3 will operate at 40gbe ethernet if possible

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#122]
So I finally shelled out for a 2nd one (1st was in the esos server).  Put the new one in primary vsphere host and rebooted.  No more 10gbe enet - it now shows as 40gbe!  (they are connected back to back.)  Supported HW page might want to indicate this.

**Comment by msmith626** [comment]
Not sure I follow... what needs to be changed on the wiki page?

--Marc

**Comment by dswartz** [comment]
On 2015-05-14 21:49, Marc A. Smith wrote:
> Not sure I follow... what needs to be changed on the wiki page?

Maybe my memory was faulty.  I thought it referred to 10gbe.  If not, 
never mind :)

**Comment by msmith626** [comment]
Ah, no problem. =)


--Marc

**Comment by dswartz** [comment]
Might still be nice to mention they support 40gbe in the right circumstances, but that's your call...

**Comment by dswartz** [comment]
I was playing with trying to get srp working and discovered that i don't in fact have connectx-3 VPI cards, but connectx-3 EN cards, so they are vanilla enet cards (albeit with QSFP+ ports).

**Comment by msmith626** [comment]
Good to know, thanks.
