### ISSUE TITLE
Missing dir /var/lock/subsys used by clvm ra

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#123]
Hi, I test latest build now and I got errors about cant write lock file by clvm resource agent. So you should include /var/lock/subsys by default, or configure ra when building.

**Comment by msmith626** [comment]
I updated the autoconf script to create this directory... committed and
pushed. New ESOS image should be available in about an hour (master).

--Marc

On Sun, May 17, 2015 at 12:15 PM, Kristian Feldsam <notifications@github.com
