### ISSUE TITLE
Missing dlm_stonith binary?

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#124]
Hi, I plays with dlm, clvm etc. and I have problem with fencing. Pacemaker fence node without problem, but to dlm is reported result 1 (error) insted of result 0 (ok). I find out, that dlm by default use fence_all dlm_stonith, but dlm_stonith binary is missing...

**Comment by feldsam** [comment]
May 17 23:48:28 storage1 dlm_controld[3307]: 145 dlm_controld 4.0.2 started 
    May 18 00:08:42 storage1 esos_tui[15223]: TUI start-up...
    May 18 00:10:34 storage1 dlm_controld[3307]: 1471 fence request 2 pid 16223 nodedown time 1431900634 fence_all /usr/sbin/stonith 
    May 18 00:10:35 storage1 dlm_controld[3307]: 1472 fence result 2 pid 16223 result 1 exit status 
    May 18 00:10:35 storage1 dlm_controld[3307]: 1472 fence status 2 receive 1 from 1 walltime 1431900635 local 1472 
    May 18 00:10:35 storage1 dlm_controld[3307]: 1472 fence request 2 no actor 
    May 18 00:11:32 storage1 dlm_controld[3307]: 1529 clvmd wait for fencing

**Comment by feldsam** [comment]
May 18 00:10:22 storage1 stonithd[2698]:   notice: handle_request: Client crmd.2702.77ac0309 wants to fence (reboot) 'storage2.feldhost.cz' with device '(any)'
	May 18 00:10:22 storage1 stonithd[2698]:   notice: initiate_remote_stonith_op: Initiating remote operation reboot for storage2.feldhost.cz: 0748bc9f-7f9c-4de7-b86b-ded093899707 (0)
	May 18 00:10:22 storage1 stonithd[2698]:   notice: can_fence_host_with_device: fence_storage2_ipmi can fence (reboot) storage2.feldhost.cz: static-list
	May 18 00:10:22 storage1 stonithd[2698]:   notice: can_fence_host_with_device: fence_storage2_pdu1 can fence (reboot) storage2.feldhost.cz: static-list
	May 18 00:10:22 storage1 stonithd[2698]:   notice: can_fence_host_with_device: fence_storage2_pdu2 can fence (reboot) storage2.feldhost.cz: static-list
	May 18 00:10:32 storage1 stonithd[2698]:   notice: log_operation: Operation 'reboot' [16076] (call 3 from crmd.2702) for host 'storage2.feldhost.cz' with device 'fence_storage2_ipmi' returned: 0 (OK)
	May 18 00:10:34 storage1 stonithd[2698]:   notice: process_remote_stonith_exec: Call to fence_storage2_ipmi for storage2.feldhost.cz on behalf of crmd.2702@storage1.feldhost.cz: OK (0)
	May 18 00:10:34 storage1 stonithd[2698]:  warning: get_xpath_object: No match for //@st_delegate in /st-reply
	May 18 00:10:34 storage1 stonithd[2698]:   notice: remote_op_done: Operation reboot of storage2.feldhost.cz by storage1.feldhost.cz for crmd.2702@storage1.feldhost.cz.0748bc9f: OK
	May 18 00:10:34 storage1 crmd[2702]:   notice: tengine_stonith_callback: Stonith operation 3/120:24:0:11cf8527-78fc-4228-a5b5-08ab6412923b: OK (0)
	May 18 00:10:34 storage1 crmd[2702]:   notice: tengine_stonith_notify: Peer storage2.feldhost.cz was terminated (reboot) by storage1.feldhost.cz for storage1.feldhost.cz: OK (ref=0748bc9f-7f9c-4de7-b86b-ded093899707) by client crmd.2702

**Comment by msmith626** [comment]
It turns out this binary is part of the dlm package, but the default/base
Makefile in the root of the source's package doesn't build it by default.
Its in the 'fence' directory... I updated the recipe in ESOS's Makefile.in
to build/install it. This has been committed and pushed.

--Marc

**Comment by feldsam** [comment]
Hello, thank You. Just to be clear, this is bug, because it prevents dlm fence node and unlock alive node(s), so all other nodes remain locked until reboot.
