### ISSUE TITLE
/mnt/conf mounted after start prevents conf_sync

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#125]
Hi, /mnt/conf is mounted after start also if in fstab is noauto option. This prevents conf_sync.sh complete job.

**Comment by msmith626** [comment]
Hi,

Not sure I follow... the 'noauto' option is in there for all esos_X file
systems purposely so they are not auto-mounted... that is, it should not be
auto-mounted on boot. The usb_sync.sh script will mount esos_conf when it
needs to.


--Marc

**Comment by feldsam** [comment]
Hi, after every machine start /mnt/conf is mounted

    /dev/sdc3                96.8M      3.1M     88.8M   3% /mnt/conf

So when you run conf_sync.sh it stops on error abou already mounted target. Solution is unmounting target or edit usb_sync.sh script to check if target is mounted already.

**Comment by feldsam** [comment]
hmm, I try to reset fstab to lates one from repo, and now its remain mounted only after first start :), so it's ok now.

**Comment by msmith626** [comment]
The esos_conf file system (at /mnt/conf) is only mounted and unmounted by the usb_sync.sh script (which is called by conf_sync.sh)... its done initially at boot, and subsequently by conf_sync.sh as you described. If the usb_sync.sh script encounters an error (now rsync) then /mnt/conf (esos_conf) could remain mounted which may be the condition you were seeing.

--Marc
