### ISSUE TITLE
Google groups blacklisting me?

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#128]
In the last couple of days, I have made multiple updates to an existing forum post, as well as new posts.  The next time I check, they are gone?

**Comment by msmith626** [comment]
Are you referring to the Google Groups service? Ah, you are, just took a
look... it appears Google thinks you are spamming them so they held the
messages (pending). I approved the messages.

--Marc

**Comment by dswartz** [comment]
WTF is their problem?  This started happening with the 1st update I did?  Thanks google :(

**Comment by dswartz** [comment]
And now I'm on the sh*tlist again.  Grrrrr....

**Comment by msmith626** [comment]
I checked the "always allow from author" button this time so hopefully it
sticks.

**Comment by dswartz** [comment]
thanks.  i wish i knew why google suddenly hates me...
