### ISSUE TITLE
DRBD Problems

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#129]
Hello, I have problem with DRBD and I think that they are related with switch to udev.

I got split brain and want to solve it. So I stop pacemaker and try to manually start drbd resource.

Here is result:

	[root@storage2 ~]# drbdadm secondary r0
	DRBD module version: 8.4.3
	   userland version: 8.4.4
	preferably kernel and userland versions should match.
	0: Failure: (127) Device minor not allocated
	additional info from kernel:
	unknown minor
	Command 'drbdsetup secondary 0' terminated with exit code 10

	[root@storage2 ~]# drbdadm connect --discard-my-data r0
	DRBD module version: 8.4.3
	   userland version: 8.4.4
	preferably kernel and userland versions should match.
	r0: Failure: (162) Invalid configuration request
	additional info from kernel:
	unknown resource
	Command 'drbdsetup connect r0 ipv4:192.168.10.2:7789 ipv4:192.168.10.1:7789 --sndbuf-size=512k --max-epoch-size=8000 --max-buffers=8000 --rr-conflict=disconnect --after-sb-2pri=disconnect --after-sb-1pri=discard-secondary --after-sb-0pri=discard-zero-changes --protocol=C --allow-two-primaries=yes --discard-my-data' terminated with exit code 10

Same error on both nodes :( Pacemaker start drbd resources without problem, both master, but with split brain (Primary/Outdated).....It's correct behaviour?

**Comment by msmith626** [comment]
Yeah, I would say that the likely culprit (udev)... I wonder if the udev
DRBD rules are messing something up, or something is different than
expected? I haven't looked at it yet, but maybe udev makes the device nodes
in /dev/drbd or something like that? I'll play with it this evening and see
what I can come up with. If you have a minute, maybe check if /dev/drbdX
exists or even /dev/drbd/rX exists?

--Marc

**Comment by feldsam** [comment]
Hi, I think that /dev/drbd0 must exists, because pacemaker run lvm, mount file system and run scst without problems.

**Comment by feldsam** [comment]
or? lvm probably can work automaticaly with both variations....

**Comment by feldsam** [comment]
ok, I go check..just a minute I boot up machine

**Comment by msmith626** [comment]
Okay, that is my first guess. If the device file location changed I may
need to update items in the TUI as well. Thanks.

**Comment by feldsam** [comment]
Hi, so I boot up and check for device. There is /dev/drbd0. Question, how can pacemaker start drbd when I can't do this manualy?

**Comment by feldsam** [comment]
What this have to do with TUI?

**Comment by msmith626** [comment]
Your particular issue has nothing to do with the TUI, this just reminded me
that I may need to check from functions in the TUI to make sure they find
the drbd device names after the move to udev.

So "/dev/drbd0" exists... is there a "/dev/drbd/" directory or something
similiar? Maybe the drbd scripts are checking that udev is enabled and
expecting a device node somewhere else? I don't think Pacemaker can start
drbd when you can't do it manually, or are you saying Pacemaker is able to
start the DRBD resources just fine, but you can't do it by hand on the
shell?

--Marc

**Comment by feldsam** [comment]
There is just /dev/drbd0....Yes, pacemaker start resource on both nodes Master, but split brain is detected. On both nodes is drbd status
    
     0: cs:WFConnection ro:Primary/Unknown ds:UpToDate/Outdated C r-----


So pacemaker decided that both nodes are master and run other resources on top of it (lvm, mount point, scst...)

**Comment by feldsam** [comment]
So I wanna resolve split brain manually, but i can't...

**Comment by feldsam** [comment]
I solved split brain by

    crm resource demote ms_drbd
    drbdadm disconnect r0
    drbdadm secondary r0
    drbdadm --discard-my-data connect r0
    # on second node
    drbdadm connect r0
    crm resource promote ms_drbd

But without pacemaker resource running it's doesn't work, why? Do I need run rc.d/rc.drbd script?

**Comment by msmith626** [comment]
Gotcha, okay, so back to the original problem/question:
[root@storage2 ~]# drbdadm secondary r0
DRBD module version: 8.4.3
   userland version: 8.4.4
preferably kernel and userland versions should match.
0: Failure: (127) Device minor not allocated
additional info from kernel:
unknown minor
Command 'drbdsetup secondary 0' terminated with exit code 10

I did a quick search and some of the reasons very for that error, it seems
in some cases there was additional information in the kernel logs. Anything
interested in there after trying to above command?


--Marc

**Comment by msmith626** [comment]
Still haven't gotten to this yet... I actually am going to be doing some DRBD stuff anyhow later this week / this weekend, so it works out perfect. I'll let you know what I find out.

--Marc

**Comment by feldsam** [comment]
Hi, drbd under pacemaker is working, but errors about version mismatch are still here.

**Comment by msmith626** [comment]
How did you end up getting it working? I believe previously you said under
Pacemaker it worked fine, but you couldn't manually do something (can't
remember what exactly, and didn't look at the previous messages).

The errors about the version mismatch will never go away... 3.14.x kernel
uses DRBD 8.4.3 and we use user-land 8.4.4 as that version fixes a bug. Its
just a warning and should be safe to ignore. I believe there is an
environment variable we can set so we don't get notified about the warning.


--Marc

**Comment by feldsam** [comment]
Hi, I play with drbd today and its working ok.
