### ISSUE TITLE
ZFS functionality would benefit by presence of arcstat.py

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#130]
https://github.com/mharsch/arcstat (this supports l2arc also).  note that this perl script requires Solaris Kstat support.  There is a perl library module for this, at https://github.com/zfsonlinux/linux-kstat.

There are a number of statistics that can be printed.  An example (running every 10 seconds):

arcsz  l2size  l2hit%  hit%
  15G    215G      40    94
  15G    215G      49    93
  15G    215G      34    96
  15G    215G      36    94
  15G    215G      38    96

(in my config, there is 32GB RAM - ZFS defaults to using 1/2 for ARC.  Given I have nothing else using RAM, I will probably set module parameter to bump ARC to 28GB).  Also have to 128GB SSD for l2arc.

**Comment by msmith626** [comment]
I'm not sure what your asking for? Are you wanting something different then
the already installed "/usr/bin/arcstat.py" script?

--Marc

**Comment by dswartz** [comment]
What I'm asking for is a good, stiff drink, since it's been one of those weeks :(  For some reason, when I tried to run arcstat.py originally it didn't find it.  I have no idea why.  Cockpit error, I assume.  Closing this, and sorry for the waste of bandwidth...

**Comment by msmith626** [comment]
No problem... there was an issue with some of the Python modules in one of
the builds you had before, and maybe that's what you were thinking of. =)
