### ISSUE TITLE
zfs import and mount code is not quite right

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#131]
We need to change the 3 lines currently there to this:

    /bin/echo "Importing ZFS pools..."
    /usr/sbin/zpool import -c /etc/zfs/zpool.cache -aN
    /usr/sbin/zpool import -d /dev/disk/by-id -aN
    /bin/echo "Mounting ZFS filesystems..."
   /usr/sbin/zfs mount -a

zvol performance can still be kind of dodgy, so a lot of people do what esos does and create a filesystem, then an appropriately sized file.  Unfortunately, as rc.2 now stands, it doesn't mount any such filesystems.

**Comment by msmith626** [comment]
So, are you saying you want to add 2 lines below this:
--snip--
/bin/echo "Importing ZFS pools..."
/usr/sbin/zpool import -c /etc/zfs/zpool.cache -aN
/usr/sbin/zpool import -d /dev/disk/by-id -aN
--snip--

You want to add this:
--snip--
/bin/echo "Mounting ZFS filesystems..."
/usr/sbin/zfs mount -a
--snip--

Is that what you're suggesting? Is that different than using /etc/fstab and
the legacy file system option with ZFS (can't remember the command/option
now...)?


--Marc

**Comment by dswartz** [comment]
Correct (at least at it currently stands.)  If you want to go the legacy mountpoint route, so that we can leverage the /var/vdisks approach in the TUI, this would not be needed.  What would you prefer?

**Comment by msmith626** [comment]
I prefer keeping it like the other file systems... we should make a ZFS
section in the wiki stating this.

**Comment by dswartz** [comment]
that's cool.  what i had to do was manually create the "lun" file in /tank/vsphere and then was able to map it, etc...

**Comment by msmith626** [comment]
Is there anything additional that needs to be done with this, or safe to close?

--Marc

**Comment by dswartz** [comment]
If we want to go with the standard /mnt/vdisks approach, at some point, we need to add the ability to create & mount zfs datasets using the legacy mountpoint, no?

**Comment by msmith626** [comment]
Yeah it already works using the legacy fstab method so let's just stick
with that, I prefer consistency.


Marc

**Comment by dswartz** [comment]
Okay, so I need to fiddle the TUI stuff that figures out filesystems and such.  I'll take a look...

**Comment by msmith626** [comment]
Yeah, I think we just need to add the ZFS file system stuff to the
createFSDialog() function and that should be it.

--Marc

**Comment by msmith626** [comment]
There were some changes recently submitted by another user for ZFS pool setup/import on boot. Is this issue safe to close, or we still have more work to do? When I wrote this before I was thinking we could still run "mkfs.zfs /dev/sda1" and get something like a file system, but I don't think that is the case -- right? If not, then I don't think we need to add anything more into the File Systems section for this. Thoughts?

--Marc

**Comment by dswartz** [comment]
I haven't seen the changes you mentioned.  The idea of 'mkfs.zfs' won't work unless you code up a wrapper.  It might be best to just close this for now...
