### ISSUE TITLE
mellanox dual-port connectx-3 results in only one usable port

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#132]
1gb e1000 renamed as enp4s0 as before
40gbe port 1 renamed as enp1s0 as before
when i tried to configure 'eth2', it fails with the following:

[   41.406133] mlx4_en: eth2: Using 64 TX rings
[   41.406134] mlx4_en: eth2: Using 8 RX rings
[   41.406135] mlx4_en: eth2:   frag:0 - size:1526 prefix:0 align:0 stride:1536
[   41.407825] mlx4_en: eth2: Initializing port
[   43.656709] mlx4_en: eth2: Link Up
[   88.143413] udevd[1941]: Error changing net interface name 'eth2' to 'enp1s0': File exists

this seems to be because the mellanox is presenting only one PCI address.  vsphere 'fixes' this by presenting these two names:
vmnic1
vmnic1000102

because the rename of eth2 fails, the interface does not come up.  i can manually configure it and bring it up, but that's obviously a hack.  if we can't deal with this like vsphere, how do i disable the nic renaming?

**Comment by msmith626** [comment]
I would think you can control/modify the udev behavior by changing/adding
udev rules to /etc/udev/rules.d/.

--Marc

**Comment by dswartz** [comment]
Yeah, I vaguely recall that from working with more recent CentOS.  I was curious where and who does the basic renaming of eth* to enp*?

**Comment by msmith626** [comment]
The udev stuff does that. You may be able to create one of the "persistent
rule" files like CentOS and other distros do by default... I should look
into making ESOS do that with eudev, but you should be able to do it by
hand too.

**Comment by dswartz** [comment]
On 2015-06-04 10:42, Marc A. Smith wrote:
> The udev stuff does that. You may be able to create one of the
> "persistent
>  rule" files like CentOS and other distros do by default... I should
> look
>  into making ESOS do that with eudev, but you should be able to do it
> by
>  hand too.

that's what has me confused, though.  something is automagically 
renaming all 3 interfaces under the sheets.  the 1gbe e1000 is eth0.  i 
can see at early bootload where the mlx4 driver is create eth1 and eth2. 
  then later, eudev is renaming the first two (based on the PCI slot 
info, I assume).  it then spits that error about eth2 due to the PCI 
info being the same (fwiw, i saw a post on a vmware forum asking about 
the weird 000102 or whatever - that is now sort of explained - vsphere 
sees the same duplicate name, so it appends some juju to the end to get 
a unique nic name).  i assume i can create my own rule to rename eth2, 
but how do i keep the default stuff from colliding with my rule?

**Comment by msmith626** [comment]
Honestly not sure... I'm not a udev expert, but this should be the same as
udev on any other Linux distro... its vanilla eudev, nothing special. I
believe it evaluates rules in /etc/udev/rules.d first and then the default
stuff in /usr/lib/udev/rules.d... so I'd creating a persistent rule file in
/etc/udev/rules.d and use that MAC (or whatever it uses to uniquely
identify an interface).

**Comment by dswartz** [comment]
On 2015-06-04 11:07, Marc A. Smith wrote:
> Honestly not sure... I'm not a udev expert, but this should be the
> same as
>  udev on any other Linux distro... its vanilla eudev, nothing special.
> I
>  believe it evaluates rules in /etc/udev/rules.d first and then the
> default
>  stuff in /usr/lib/udev/rules.d... so I'd creating a persistent rule
> file in
>  /etc/udev/rules.d and use that MAC (or whatever it uses to uniquely
>  identify an interface).

okay, i'll give it a shot later.  thanks!

**Comment by dswartz** [comment]
On 2015-06-04 11:07, Marc A. Smith wrote:
> Honestly not sure... I'm not a udev expert, but this should be the
> same as
>  udev on any other Linux distro... its vanilla eudev, nothing special.
> I
>  believe it evaluates rules in /etc/udev/rules.d first and then the
> default
>  stuff in /usr/lib/udev/rules.d... so I'd creating a persistent rule
> file in
>  /etc/udev/rules.d and use that MAC (or whatever it uses to uniquely
>  identify an interface).

well, this is a mystery.  i tried a dozen different ways to do the 
above, with no effect (not even any error messages in the logs...)  so i 
found this: 
http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/#idontlikethishowdoidisablethis

I tried symlinking thusly:

lrwxrwxrwx    1 root     root             9 Jun  5 17:20 
80-net-name-slot.rules -> /dev/null

i confirmed that i did do conf_sync.sh before reboot, and the symlink 
*does* show up after reboot, but it ain't working.  the only thing that 
seems to work is option #4:

"You pass the net.ifnames=0 on the kernel command line"

I did this, and got eth0, eth1 and eth2 (this is in a VM, so I won't be 
constantly rebooting the production appliance...) I would be willing to 
go this route anyway, but I'm not sure how/where to change the default 
grub options for ESOS?

p.s. I was mentioning the weird mellanox 2-port thing at lunch, and a 
coworker who works on linux said 'Oh yeah!  They present both ports as 
one PCI function!  Thanks mellanox!" :)

**Comment by msmith626** [comment]
For GRUB options:
mount /boot
vi /boot/grub/grub.conf
(Set GRUB options.)
umount /boot

Although currently you'll need to re-add GRUB options if you
upgrade/install again though... in the future we'll change this.

**Comment by dswartz** [comment]
On 2015-06-05 13:49, Marc A. Smith wrote:
> For GRUB options:
>  mount /boot
>  vi /boot/grub/grub.conf
>  (Set GRUB options.)
>  umount /boot
> 
>  Although currently you'll need to re-add GRUB options if you
>  upgrade/install again though... in the future we'll change this.

ah, thanks.  i was thinking it was going to be /mnt/boot or somesuch.  i 
wish i knew what the problem was, but the udev stuff is dark juju (for 
me anyway). i've found a ton of posts on different forums with people 
pulling their hair out trying to get sh*t like this to just work 
sanely...

**Comment by dswartz** [comment]
okay, that's weird.  rebooted the VM and the nics are now eth*, but the 
LAN didn't come up.  went into TUI and restarted networking, and it says 
it couldn't access enp2s0 (old renamed name?)  TUI has stale info?

**Comment by msmith626** [comment]
Yeah, if the Ethernet interface name changed (eg, enp2s0 -> eth0) the
TUI/configuration doesn't know that... easiest to just edit
/etc/network.conf and replace the string.

--Marc

**Comment by dswartz** [comment]
Yeah, it leaves the old one *and* the new one.  Okay, thanks!

**Comment by dswartz** [comment]
Okay, this turned out to be way more trouble than it was worth.  Two issues that bit me (one of them not esos fault, and one a legitimate esos issue).  It turns out the rc.network script is hard coded to handle certain device names, so passing net.ifname=0 on the grub command line did in fact prevent the devices from being renamed, but the rc.network script couldn't handle 'eth*' names.  I modified the script, but it still failed.  Deeper investigation reveals that even if you tell linux to NOT rename the devices, it still creates them as these:

lrwxrwxrwx    1 root     root             0 Jun  7 23:08 /sys/class/net/enp1s0 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/net/enp1s0
lrwxrwxrwx    1 root     root             0 Jun  7 23:08 /sys/class/net/enp4s0 -> ../../devices/pci0000:00/0000:00:1c.4/0000:04:00.0/net/enp4s0

for now, i think i'm just going to have to live with 'only' 1gb connection from the backup vsphere host...  and/or check to see if the PCI botch is something that can be fixed with a mellanox FW update...

**Comment by dswartz** [comment]
Aha, a linux guy at work told me the web post I saw was incomplete.  You need to say:

net.ifnames=0
AND
biosdevname=0

I will give that a try, shortly.  If it works, do you have any objection to my opening a PR to enhance rc.network to allow 'eth*' as well?

**Comment by msmith626** [comment]
Yeah, no objection at all... its an easy add, just need to update the OR
logic lines in that Perl script to look for "eth" too. Nice find, hopefully
that works out for you! =)

**Comment by dswartz** [comment]
I would love to figure out how to make this work 'the right way' (e.g. 
the hack vsphere does where if they can't rename the interface because 
it already exists, they append magic juju [based on PCI fields?])

**Comment by dswartz** [comment]
Okay, the above worked perfectly.  Closing this.  I will open a separate issue for the PR.
