### ISSUE TITLE
WRITE SAME failed. Manually zeroing

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#133]
Ubuntu 14.04 server on LUN served up by ESOS (on a vdisk_fileio sitting on a ZFS filesystem).  No messages I can see from ESOS.  Google isn't real helpful.  Is this an issue?  Comes from VAAI?

**Comment by msmith626** [comment]
Not sure where that message is coming from? ESOS?

**Comment by dswartz** [comment]
Sorry, I was unclear.  That was printed in the ubuntu VM console.  I thought it was trying to do a vaai operation or something.  Googling around some more, it looks like it may be a bug in the linux scsi driver that triggers under vmware when tools are not (yet) installed.  Closing...
