### ISSUE TITLE
Problem with versioning stable/development branch

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#138]
Hello, I see divergence between stable and development branch and misunderstanding git development flow model.

There are IMPORTANT fixes in development "master" branch, 2months old, which are not in stable branch. For example DLM Stonith missing bin. How can somebody run cluster without dlm stonith? It's strange.

Why you don't accommodate GIT FLOW pattern? It's simple to use.

http://danielkummer.github.io/git-flow-cheatsheet/

**Comment by msmith626** [comment]
Hi Kristian,

I'm sure a lot of it comes my naiveness with Git and software versioning...
I had read a number of articles on Git and branching/versioning and here is
what I decided at the time:
- 'master' branch is bleeding edge, for development (not stable/production
as most Git articles describe)... all new features, changes, additions go
into this branch
- '0.1.x' branch is the only current stable branch for now... no new
features, only bug fixes

If you're familiar with the *BSD projects, this is closer to how I want the
versioning/releases with ESOS... we'll have a bleeding edge "current"
branch (master) and then one or more stable branches (0.1.x for now).

So, I apologize if I didn't include some commits that you felt were bug
fixes as I may have considered them features or additions. Let me know what
they are and I'll review them again.

And for DLM STONITH -- I had never heard or used this until you mentioned
it (or had I ever read any cluster articles about it)... lots running in
production without issue, and others are/have as well. (Not saying that
feature is a bad thing, just doesn't appear to be a requirement.)


--Marc

**Comment by feldsam** [comment]
Hi,

I made cluster according your blog post from 2013. So I have drbd, lvm, scst. Lvm requires cLvm which requires dlm. I don't know, if you test several scenarios, but when something go bad on one node, dlm lock clvm and request for stonith bad node via dlm_stonith which communicate with pacemaker. Without dlm_stonith, dlm can't shot node and alive node remains locked

**Comment by feldsam** [comment]
I don't use dlm_stonith bin directly, dlm itself use it for fencing.

**Comment by msmith626** [comment]
Is this the commit you're referring to:
https://github.com/astersmith/esos/commit/5207d20d98293c96c335112db75afcf29f632642

?? If so, I'll get this added to 0.1.x.

--Marc

**Comment by feldsam** [comment]
Hi, yes it's that commit. What you think about it now? Am I right? Do you use cLVM without stonith in production?

**Comment by msmith626** [comment]
Yes, I use cLVM in production... I do use fencing (STONITH) but not that
fencing method (IPMI to reset/power-cycle is the fencing method for one of
these setups).

I'll get the change into 0.1.x and produce a new version.


--Marc

**Comment by feldsam** [comment]
hmm, I think we do not understand...  I also configure for fencing just and only pacemaker. I nothing to do with dlm_stonith, BUT... I do some tests, like pull out network cable or power cable and clvm locks, because its waiting for fence, which is by default initialized by dlm control daemon. I was confused about it, asking yourself why dlm cant fence??? and after enabling debug and looking to logs I figure out that dlm_stonith is missing.

dlm_stonith is proxy for fencing via stonith/pacemaker and without it clvm/dlm cant fence node and remains locked.

I dont know, if you test this scenario in your clvm two node cluster, but I believed that on build without dlm_stonith it just lock and remain locked.

In my opinion this is critical bug, because when one node fail, second one locks and whole cluster is die.

**Comment by msmith626** [comment]
Gotcha; I haven't forgotten about this, and I will include the dlm_stonith
binary in the 0.1.x branch... currently wrapping up testing of the SCST
3.0.x version in this branch and I'll include both which will be version
0.1.5 -- sorry for the delay! Should have it complete by Monday or Tuesday
of this coming week.

--Marc

**Comment by feldsam** [comment]
Ok, no problem, I am on master branch. I want just point to this problem.

**Comment by msmith626** [comment]
The dlm_stonith binary has been added to 0.1.5.

--Marc
