### ISSUE TITLE
Missing _sqlite3.so

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#139]
Traceback (most recent call last):
  File "./migrate_blocks_freq.py", line 31, in <module>
    import sqlite3 as sqlite
  File "/usr/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/lib/python2.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

**Comment by msmith626** [comment]
Looking at this now...

**Comment by msmith626** [comment]
Hi Kristian,

ESOS currently does not include the SQLite library which is why the Python
module is not built. Sound like a worthy addition?


--Marc

**Comment by feldsam** [comment]
I wanna use btier migration python script which use sqlite. Probably you can also add that script to bin.

btier-src/tool/contribute/migrate_blocks_freq.py

**Comment by msmith626** [comment]
This has been resolved in 0.1.5 (posted) -- includes the Python sqlite3 fix and the BTIER Python script.

--Marc
