### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#140]
Hi, I playing and when I put storage2 to standby "crm node standby" and after it back to online "crm node online" following message appears and storage1 freeze

Message from syslogd@storage1 at Fri Aug 28 16:09:46 2015 ...
storage1 kernel: [2497641.773317] IP: [<ffffffff817ee088>] sock_sendmsg+0x45/0x7a

Message from syslogd@storage1 at Fri Aug 28 16:09:46 2015 ...
storage1 kernel: [2497641.676651] BUG: unable to handle kernel NULL pointer dereference at 0000000000000028

Message from syslogd@storage1 at Fri Aug 28 16:09:46 2015 ...
storage1 kernel: [2497644.776876] RIP  [<ffffffff817ee088>] sock_sendmsg+0x45/0x7a

**Comment by msmith626** [comment]
I assume this is with kernel 3.14.36? Is there a full stack trace in
/var/log/kern.log? Or its completely frozen and you can't get to anything
on 'storage1'? What version of ESOS?

--Marc

On Fri, Aug 28, 2015 at 11:20 AM, Kristian Feldsam <notifications@github.com

**Comment by feldsam** [comment]
Hi, I just updated to latest dev version and it;s ok now.
