### ISSUE TITLE
Update LVM2

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#141]
Hi, would you update LVM to latest Version 2.02.129 - 26th August 2015

In 2.02.126 is fix abou clvm freeze
  Fix clvmd freeze if client disappears without first releasing its locks.

I have problems with clvm, hope to this help

**Comment by msmith626** [comment]
Yes, I'll do a test build on my machine and then push the changes.

--Marc

**Comment by msmith626** [comment]
This change has been pushed to master (5bbe67845da564dbdbe02505feb85dadc71410f0); the Buildbot should have the new image posted in about an hour or so.

--Marc

**Comment by feldsam** [comment]
Thank you
