### ISSUE TITLE
Too long startup time

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#143]
Hi, I see that you refactor installation to support two slots. I have usb 2.0 and after grub there is probably some loading of whole root image to memory, which takes long time. Also, when I modify some system files for testing, I can't it sync to usb, because of root image.

Can you add option to use oldtime install? Or don't use images, and instead put root files to separate directories on usb?

When I talking about high/low firmware images few months ago, I think about two usb sticks....

**Comment by msmith626** [comment]
Hi,

I actually find the boot process now faster than the previous method:
- Before, as we do in 0.1.x, at boot the root FS is read via find and piped into cpio which then writes out of the files/etc. to our tmpfs file system.
- With the new system, the image is already a cpio archive, compressed, and then image is extracted, piped to cpio which puts it on the tmpfs file system.

I haven't done testing, so I supposed it could be a bit slower, but its here to stay. Get a better USB flash drive (a higher-end USB 2.0 device).

For modifying the image (persistent changes) I still need to complete the wiki documentation, but you'll do it like this:
- mkdir /tmp/mount
- mount /mnt/root
- archivemount PRIMARY-root.cpio.bz2 /tmp/mount

Then make your changes under /tmp/mount and when done:
- umount /tmp/mount
- umount /mnt/root

That's the gist of it for now, maybe some supporting shell scripts to automate it?


--Marc

**Comment by feldsam** [comment]
Hi, thank You for explanation how to edit root file system.

I made tests,

This screen take 2m26s
![screen shot 2015-08-29 at 18 46 04](https://cloud.githubusercontent.com/assets/951648/9563560/f0bbce2c-4e87-11e5-9879-0e5ac4719e3b.png)

On 3m20s this screen appears
![screen shot 2015-08-29 at 18 49 58](https://cloud.githubusercontent.com/assets/951648/9563565/04640c64-4e88-11e5-91a8-9fcfe81eb12a.png)

And machine is booted on 5m37s

I have USB3 drive in USB2 port http://usb.userbenchmark.com/Adata-S102-Pro-USB-30-16GB/Rating/1346

You have which one?

**Comment by msmith626** [comment]
The BIOS POST -> GRUB -> kernel load times wouldn't have been affected by
this change (the slots install system). Only from the "Initializing root
file system..." screen to when init is called would have been affected. I
didn't notice any substantial time difference, but I didn't time it with a
stopwatch either.

I've used several different brands of drives over the years, SanDisk USB
3.0 something (not sure of model) seems to have work the best so far.
Patriot Memory devices work well too if I recall right.

Thanks for the information!


--Marc
