### ISSUE TITLE
Kernel issue

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#144]
Hi, right now whole cluster goes down :((( I am very disappointed, I working on it whole night, to figure out other problems and new appeared :(

![screen shot 2015-08-29 at 12 45 19](https://cloud.githubusercontent.com/assets/951648/9561596/0fac0db0-4e4c-11e5-9594-1eda870b29e7.png)
![screen shot 2015-08-29 at 12 45 08](https://cloud.githubusercontent.com/assets/951648/9561597/0fcc2924-4e4c-11e5-9933-11fff258ba7a.png)
![screen shot 2015-08-29 at 12 43 54](https://cloud.githubusercontent.com/assets/951648/9561598/0fd0c646-4e4c-11e5-811d-a7f19b4a9ea6.png)

**Comment by msmith626** [comment]
Any chance you can get the full trace (the top part) from the machine? Wow, it looks like it happened on both nodes at the same time? What triggered it?

--Marc

**Comment by feldsam** [comment]
I can't replicate this behavior, I just restarted ms_scst resource and them start up initiator....

**Comment by feldsam** [comment]
Hi, I test to start/stop ms_scst resource and bug appears on one node now, but I cant get trace, node is unresponsive and them fenced.

**Comment by feldsam** [comment]
Can be triggered by bad kernel module options? I have this in modprobe.conf

    options qla2xxx_scst ql2xenablemsix=0

I I do mistake and also added  qlini_mode=disabled

   options qla2xxx_scst ql2xenablemsix=0 qlini_mode=disabled

**Comment by msmith626** [comment]
Eek, what version of ESOS are you using? Are you in fact using qla2xxx_scst
or is that remnants left over from an old ESOS upgrade? We've now went back
to the original (in-tree) QLogic target driver from SCST.

Check with "modprobe | grep qla2xxx" -- If its "qla2xxx_scst" that is the
QLogic provided driver which has been deemed unstable, if its just
"qla2xxx" you're good.


--Marc

On Sat, Aug 29, 2015 at 12:25 PM, Kristian Feldsam <notifications@github.com

**Comment by feldsam** [comment]
Hi, latest master (ESOS - Enterprise Storage OS master_5bbe678_dgv)

Ahaa, but old driver working good for me, wouldn't be change of driver issue with my initiators?

**Comment by msmith626** [comment]
Maybe that is the culprit for your kernel panics? I couldn't see enough of
the message to tell...

Its fine with the initiator names you have (no difference to initiators
that I can tell).

On Sat, Aug 29, 2015 at 12:31 PM, Kristian Feldsam <notifications@github.com

**Comment by msmith626** [comment]
But if you're using image from ESOS (esos-project.com) then latest master
by default uses the in-tree QLogic driver, no longer QLogic provided
driver. And that is latest, so you're actually using the in-tree driver.
Update your modprobe.conf to use your parameters for the right module name
(qla2xxx not qla2xxx_scst).

--Marc

**Comment by feldsam** [comment]
Hi, I updated, but it has nothing to do with this issue.

**Comment by feldsam** [comment]
Something interesting from kern.log

	Aug 29 19:10:48 storage2 kernel: [ 1340.609073] bio: create slab <bio-2> at 2
	Aug 29 19:10:48 storage2 kernel: <27>[ 1340.937863] udevd[8358]: conflicting device node '/dev/mapper/r0-one' found, link to '/dev/dm-7' will not be created
	Aug 29 19:10:48 storage2 kernel: <27>[ 1340.937948] udevd[8305]: conflicting device node '/dev/mapper/r0-vm_images' found, link to '/dev/dm-1' will not be created
	Aug 29 19:10:48 storage2 kernel: <27>[ 1340.967940] udevd[8298]: conflicting device node '/dev/mapper/r0-images' found, link to '/dev/dm-0' will not be created
	Aug 29 19:10:48 storage2 kernel: <27>[ 1340.968937] udevd[8314]: conflicting device node '/dev/mapper/r0-boot_node1' found, link to '/dev/dm-2' will not be created
	Aug 29 19:10:48 storage2 kernel: <27>[ 1340.969238] udevd[8323]: conflicting device node '/dev/mapper/r0-boot_node2' found, link to '/dev/dm-3' will not be created
	Aug 29 19:10:48 storage2 kernel: <27>[ 1340.969450] udevd[8332]: conflicting device node '/dev/mapper/r0-boot_node3' found, link to '/dev/dm-4' will not be created
	Aug 29 19:10:48 storage2 kernel: <27>[ 1340.970041] udevd[8348]: conflicting device node '/dev/mapper/r0-test' found, link to '/dev/dm-8' will not be created
	Aug 29 19:10:48 storage2 kernel: <27>[ 1340.970264] udevd[8125]: conflicting device node '/dev/mapper/r0-boot_node4' found, link to '/dev/dm-5' will not be created
	Aug 29 19:10:48 storage2 kernel: <27>[ 1340.975001] udevd[8350]: conflicting device node '/dev/mapper/r0-boot_node5' found, link to '/dev/dm-6' will not be created

**Comment by msmith626** [comment]
Hi Kristian,

In the 'master' branch we've updated to Linux 4.1.11. I'd be curious if you still experience this kernel bug in the latest master-branch package?


--Marc

**Comment by feldsam** [comment]
Hi, I am on this revision https://github.com/astersmith/esos/commit/1af91c6dc4140c2f56d1dbe02b10ecd82f7262dc

So kernel version 3.14.36-esos.prod #1 SMP Sat Aug 29 19:14:34 EDT 2015 x86_64 GNU/Linux

**Comment by feldsam** [comment]
Hi, I updated to 16/11 master bracnh, so kernel 4.x and its working good

**Comment by msmith626** [comment]
Thanks for the update Kristian.
