### ISSUE TITLE
Initiators hangs

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#145]
Hi,

I testing whole night and figure out, that initiators freeze also if just one of all targets are disabled, no matter if is it active or nonoptimized...

When I testing this few months ago, initiators detect faulty path a keep working

Edit:
I open admin interfaces on fabric switches and test disable/enable targets. I surprised that when I disable target, FC card switch to initiator mode. It's normal? This probably confuse my initiators?

Wouldn't be better to disable whole FC card when target is disabled/scst stopped?

**Comment by msmith626** [comment]
modinfo qla2xxx | grep qlini_mode
parm:           qlini_mode:Determines when initiator mode will be enabled. Possible values: "exclusive" (default) - initiator mode will be enabled on load, disabled on enabling target mode and then on disabling target mode enabled back; "disabled" - initiator mode will never be enabled; "enabled" - initiator mode will always stay enabled.

It depends on what initiator mode setting you use for the qla2xxx module... so it sounds like you'd want to set qlini_mode to "disabled" in /etc/modprobe.conf for qla2xxx.


--Marc

**Comment by feldsam** [comment]
Ok, this issue is solved by module setting

    qlini_mode=disabled

This should be outlined in docs.
