### ISSUE TITLE
Feature request - add NodeJS support

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#148]
Hi,

I would like to write daemon, which manage:
- CRUD of LUNs
- ALUA Device groups
- ALUA States
- API
- In future some web interface

I am comfortable with nodejs.

I like to:
- create, update, delete LUNs via API
- even distribute LUNs on storage nodes
 - half of LUNs has state active on storage1 and standby on storage2; and vice versa
- update ALUA states on both nodes

I use this in custom storage driver for OpenNebula. Other people can find API useful too.

**Comment by msmith626** [comment]
Hi Kristian,

Funny you ask about this feature, as we already have a project under way that provides this "daemon" functionality which provides an API to ESOS for all of the functions you mentioned, plus many more. I'll let you know when we get a bit further along.


--Marc

**Comment by feldsam** [comment]
Nice to hear it, some time frame? Can I help with something?

**Comment by msmith626** [comment]
Yeah, I'll give you more details soon.

Marc

**Comment by feldsam** [comment]
Hi, any news?

**Comment by msmith626** [comment]
Hi,

Sorry, no, not yet. Should have some more information in the next month or
two. A substantial amount of the work is complete, so getting close!


--Marc

**Comment by feldsam** [comment]
Hello, any news?

**Comment by msmith626** [comment]
Sorry Kristian, we're running behind schedule. =(

Hopefully mid-January is the new target date -- I think you'll like it and
will be worth the wait.
