### ISSUE TITLE
Unable to build zfs/spl due to kernel lock configuration

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#149]
Fetched latest esos master (I'd rather have a stable snapshot, but that apparently doesn't support ZFS).  Anyway, I then fetched 0.6.4.2 spl/zfs tarballs, renamed them to 0.6.4 (after doing 'make fetch', of course.)  Did 'make extract'.  Then when doing 'make build', zfs build fails with:

checking whether modules can be built... yes
checking whether Linux was built with CONFIG_DEBUG_LOCK_ALLOC... yes
checking whether mutex_lock() is GPL-only... yes
configure: error: 
        *** Kernel built with CONFIG_DEBUG_LOCK_ALLOC which is incompatible
        *** with the CDDL license and will prevent the module linking stage
        *** from succeeding.  You must rebuild your kernel without this
        *** option enabled.
make: *** [esos_kernels] Error 1

**Comment by dswartz** [comment]
Hmmm, I don't care about the debug config.  I wonder if I can do the configuration to say no to the enable_debug config option?  Trying that now...

**Comment by dswartz** [comment]
No joy :(  I'm going to re-do the make with '-i' and hope it generates a usable non-debug image...

**Comment by dswartz** [comment]
No joy there either.  Something must have changed with the default linux kernel build options since the last time I built zfs/esos :(

**Comment by msmith626** [comment]
Hi Dan,

Sorry for the delay... there were some additional debugging options added to both kernel configs (-prod and -debug) some weeks back (in 0.1.x and master).

So it looks like just the -debug config:
$ cat misc/linux-3.14.36-debug.patch | grep CONFIG_DEBUG_LOCK_ALLOC
-# CONFIG_DEBUG_LOCK_ALLOC is not set
+CONFIG_DEBUG_LOCK_ALLOC=y

It's probably a good thing to keep for debugging (with the -debug kernel)... I'll update the Makefile to disable this option when ZFS is enabled. Can you make sure this is the only fix/change needed by modifying the misc/linux-3.14.36-debug.patch file and removing that option (comment out). Should have this fixed on master shortly. Let me know if your successful with that change I described.


--Marc

**Comment by dswartz** [comment]
Giving that a shot now.  Thanks!

**Comment by dswartz** [comment]
The patch failed.  I think it's because the patch directive for that block stipulates 14 lines being replaced by 18 lines, and describes the old and new lines.  I thought of changing the new line to be also a 'not set', but wasn't sure patch would like that (and it takes awhile to hit the failure...)  I'm trying this by just deleting that entire patch block, since it is specific to various debug things (which I don't care about anyway...)  Probably not the cleanest way to roll, but...

**Comment by msmith626** [comment]
Sorry, I should have been clearer: yeah, you can't modify a patch like
that... you can apply the patch, modify the file, then regenerate the patch
with diff, or you could try changing the line in the patch file (instead of
removing it (eg, set it to the same # comment line).

--Marc

**Comment by dswartz** [comment]
Build successful.  Testing now...

**Comment by dswartz** [comment]
Maybe not so successful :(  I didn't see any obvious errors, but when I booted from the new USB install, there were no /dev/disk* items.  Looking through the logs revealed no udev binaries.  Hmmm.  Don't see how the debug patch change affected that.  Possibly an issue with the new usb stick?  I'm building a new non-zfs package to compare against. Also, will make sure the usb stick is big enough and formatted properly and rewrite it.

**Comment by dswartz** [comment]
Kinda stuck here.  I created a fresh usb stick with vanilla 0.1.5 and /dev/disk-by-id is there as expected.  When I built out of master + zfs, that directory seems to be missing :(

**Comment by msmith626** [comment]
Okay, I'm available tonight, sorry for all the delays! So, vanilla 0.1.5
doesn't use udev, only builds from the master branch do. Did you try using
the latest build from the master branch (vanilla package available for
download):
http://download.esos-project.com/packages/master/esos-master_1af91c6_dgv.zip

This will be everything except ZFS for your testing. Also, did I catch that
you manually changed the ZFS version when building ESOS, or are you using
the versions of zfs/spl that is tries to fetch?


--Marc

**Comment by dswartz** [comment]
Yes, I installed tarballs for 0.6.4.2 but renamed them to 0.6.4 since the build system seems to have the release hardcoded and I didn't know how to change it :)  That said, is that wrong?  I think the udev message might have been a red herring, but in fact, /etc/disk-by-id does not exist in the master+zfs I built...  I'm doing another build from scratch now...

**Comment by msmith626** [comment]
That should be okay as a stop-gap solution, let me know you'd like the
versions of zfs/spl updated in master and I can do that (I assume you're
testing the latest versions).

The directory "/dev/disk-by-id" (I assume dev not etc) is not supposed to
exist in builds from master since in master we use udev and not mdev; the
directory is actually "/dev/disk/by-id/" in these (note /dev/disk/ and the
other directories under it created by udev).


--Marc

**Comment by dswartz** [comment]
The problem is that none of that stuff was there.  No /dev/disk stuff at all and no udev binaries...

**Comment by dswartz** [comment]
0.6.5 should be out soon with a ton of stability and performance fixes, so I'm fine waiting for that and sticking with 0.6.4.2 for now...

**Comment by msmith626** [comment]
So, to recap, the udev problem was a one-off issue and works as expected
now? Also, changing the that kernel option solved the build issue with ZFS,
correct?

--Marc

**Comment by dswartz** [comment]
Sorry for confusion.  I did in fact solve the build problem.  I don't yet know if the device name stuff works or not.  Build is not done yet.  It is midnight here so I am going to bed.  Well check tomorrow...

**Comment by dswartz** [comment]
Still no joy.  Did a fresh build from master+zfs.  Put on brand-new flash drive.  Rebooted.  No /dev/disk stuff at all.  Looking at /var/log/boot, I see:

[root@esos ~]# grep udev /var/log/boot
Sun Sep  6 10:37:31 2015: Starting udevd...
Sun Sep  6 10:37:31 2015: /etc/rc.d/rc.udev: line 14: /usr/sbin/udevd: No such file or directory
Sun Sep  6 10:37:31 2015: /etc/rc.d/rc.udev: line 16: /usr/sbin/udevadm: No such file or directory
Sun Sep  6 10:37:31 2015: /etc/rc.d/rc.udev: line 17: /usr/sbin/udevadm: No such file or directory
Sun Sep  6 10:37:31 2015: /etc/rc.d/rc.udev: line 20: /usr/sbin/udevadm: No such file or directory
Sun Sep  6 10:37:51 2015: /etc/rc.d/rc.sysinit: line 69: /usr/sbin/udevadm: not found

So the build is f*cking up somehow?

**Comment by msmith626** [comment]
Yeah, I'd say so... are you sure running 'make' is completing without
errors? Type 'make' again in that directory to see if all recipes are
complete.

--Marc

**Comment by dswartz** [comment]
Just got back.  Build still running.  I did script into a log file.  I had to say 'make -I' or the name blows up due to lack of gtk doc package....

**Comment by msmith626** [comment]
Any luck Dan? Also, it sounds like your build is taking a long time -- you
are aware of the '-j' option for make?

--Marc

**Comment by dswartz** [comment]
I had not been running with '-j' to try to make things more predicable.  It blew up.  The build message seems to imply that gtk-doc is non-fatal, but when I ran without '-i' it aborts right after that.  It looks like it's trying to build eudev?  I'm running again with '-i' (not from scratch) into a logfile to see if I can find out what is wrong...

**Comment by msmith626** [comment]
If its not building the "eudev" recipe, just type "make eudev" and that
might be cleaner output.

**Comment by dswartz** [comment]
I was hoping to get this resolved over the 3-day weekend, but it looks like not.  So I'm putting the production SAN back on 0.1.5.  I'm still going to get to the bottom of this, but I just realized I don't need to keep things offline to do so.  I can create an esos VM with an 8GB (boot/root) disk and a couple of 32GB "data" disks, and test things there (assuming there is in fact a build issue...)

**Comment by dswartz** [comment]
I discovered the hard way that parallel builds require quite a bit more memory for my buildbot VM or I get random OOM failures.

**Comment by dswartz** [comment]
Sigh.  And now download.esos-project.com is no longer responding to http :(

**Comment by msmith626** [comment]
Are you still locked out? Let me know -- you may have tripped the
PF-attack-rules on that box.

--Marc

**Comment by dswartz** [comment]
Still locked out, yes...

**Comment by dswartz** [comment]
All set now.  I'm not sure what is going on, but eudev does not build at all.  One confusing thing about the build process is that there are apparently all kinds of errors&warnings that seem to be okay.  One that isn't that blows up the eudev build at the end:

checking for gtk-doc... no
configure: WARNING:
  You will not be able to create source packages with 'make dist'
  because gtk-doc >= 1.18 is not found.
checking for gtkdoc-check... no
checking for gtkdoc-check... no
checking for gtkdoc-rebase... no
checking for gtkdoc-mkpdf... no
checking whether to build gtk-doc documentation... no
checking for GTKDOC_DEPS... no
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'
make: *** [eudev] Error 1

**Comment by msmith626** [comment]
Yeah, pretty much all builds from source contain warnings and even some
errors that are ignored by make... this error is not ignored so it fails. I
would suspect something from this being the problem:
        $(QUIET) if [ ! -f "$(tgt_src_dir)/configure" ]; then \
          cd $(tgt_src_dir) && ./autogen.sh; \
        fi

Since it doesn't look like Makefile.in exists... can you post the output
above that... actually, do this first (from the root of the ESOS source
directory):
cd work/build
rm -rf eudev-3.1.2
cd -
make extract
make eudev > /tmp/out 2>&1

Then post that /tmp/out file.


--Marc

**Comment by dswartz** [comment]
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./config.guess'
libtoolize: copying file `./config.sub'
libtoolize: copying file `./install-sh'
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:14: require Automake 1.13, but have 1.11.3
autoreconf: automake failed with exit status: 1
cd /root/esos/work/build/eudev-3.1.2 && PATH=$PATH:/root/esos/work/image/usr/bin \
        BLKID_CFLAGS="-I/root/esos/work/image/usr/include" \
        BLKID_LIBS="-lblkid" ./configure --prefix=/usr \
        --disable-selinux --disable-gudev --disable-kmod --disable-silent-rules
checking for gcc... gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include accepts -g... yes
checking for gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/bin/bash: /root/esos/work/build/eudev-3.1.2/missing: No such file or directory
configure: WARNING: `missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking dependency style of gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include... none
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 3458764513820540925
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include supports -fno-rtti -fno-exceptions... no
checking for gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include option to produce PIC... -fPIC -DPIC
checking if gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include PIC flag -fPIC -DPIC works... yes
checking if gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include static flag -static works... yes
checking if gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include supports -c -o file.o... yes
checking if gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include supports -c -o file.o... (cached) yes
checking whether the gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether ln -s works... yes
checking for a sed that does not truncate output... (cached) /bin/sed
checking for grep that handles long lines and -e... (cached) /bin/grep
checking for gawk... (cached) gawk
checking for gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include option to accept ISO C99... -std=gnu99
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include -idirafter /root/esos/work/image/usr/include/c++/4.4.5 -idirafter /root/esos/work/image/usr/include/c++/4.4.5/x86_64-unknown-linux-gnu accepts -g... yes
checking dependency style of g++ -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include -idirafter /root/esos/work/image/usr/include/c++/4.4.5 -idirafter /root/esos/work/image/usr/include/c++/4.4.5/x86_64-unknown-linux-gnu... none
checking how to run the C++ preprocessor... g++ -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include -idirafter /root/esos/work/image/usr/include/c++/4.4.5 -idirafter /root/esos/work/image/usr/include/c++/4.4.5/x86_64-unknown-linux-gnu -E
checking for ld used by g++ -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include -idirafter /root/esos/work/image/usr/include/c++/4.4.5 -idirafter /root/esos/work/image/usr/include/c++/4.4.5/x86_64-unknown-linux-gnu... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include -idirafter /root/esos/work/image/usr/include/c++/4.4.5 -idirafter /root/esos/work/image/usr/include/c++/4.4.5/x86_64-unknown-linux-gnu linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include -idirafter /root/esos/work/image/usr/include/c++/4.4.5 -idirafter /root/esos/work/image/usr/include/c++/4.4.5/x86_64-unknown-linux-gnu option to produce PIC... -fPIC -DPIC
checking if g++ -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include -idirafter /root/esos/work/image/usr/include/c++/4.4.5 -idirafter /root/esos/work/image/usr/include/c++/4.4.5/x86_64-unknown-linux-gnu PIC flag -fPIC -DPIC works... yes
checking if g++ -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include -idirafter /root/esos/work/image/usr/include/c++/4.4.5 -idirafter /root/esos/work/image/usr/include/c++/4.4.5/x86_64-unknown-linux-gnu static flag -static works... yes
checking if g++ -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include -idirafter /root/esos/work/image/usr/include/c++/4.4.5 -idirafter /root/esos/work/image/usr/include/c++/4.4.5/x86_64-unknown-linux-gnu supports -c -o file.o... yes
checking if g++ -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include -idirafter /root/esos/work/image/usr/include/c++/4.4.5 -idirafter /root/esos/work/image/usr/include/c++/4.4.5/x86_64-unknown-linux-gnu supports -c -o file.o... (cached) yes
checking whether the g++ -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include -idirafter /root/esos/work/image/usr/include/c++/4.4.5 -idirafter /root/esos/work/image/usr/include/c++/4.4.5/x86_64-unknown-linux-gnu linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking how to run the C preprocessor... gcc -specs=/root/esos/work/esos_build.spec -nostdinc -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include -idirafter /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed -idirafter /root/esos/work/image/usr/include -idirafter /root/esos/work/kernel_headers/include -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for m4... /usr/bin/m4
checking for xsltproc... /usr/bin/xsltproc
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/mount.h usability... yes
checking sys/mount.h presence... yes
checking for sys/mount.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/statvfs.h usability... yes
checking sys/statvfs.h presence... yes
checking for sys/statvfs.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/vfs.h usability... yes
checking sys/vfs.h presence... yes
checking for sys/vfs.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking mtd/mtd-user.h usability... yes
checking mtd/mtd-user.h presence... yes
checking for mtd/mtd-user.h... yes
checking linux/btrfs.h usability... yes
checking linux/btrfs.h presence... yes
checking for linux/btrfs.h... yes
checking for uid_t in sys/types.h... yes
checking for inline... inline
checking for mode_t... yes
checking for pid_t... yes
checking for struct stat.st_rdev... yes
checking whether getrandom is declared... no
checking whether gettid is declared... no
checking whether name_to_handle_at is declared... no
checking whether accept4 is declared... yes
checking whether mkostemp is declared... no
checking size of pid_t... 4
checking size of uid_t... 4
checking size of gid_t... 4
checking size of dev_t... 8
checking size of time_t... 8
checking size of rlim_t... 8
checking for unistd.h... (cached) yes
checking for working chown... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for _LARGEFILE_SOURCE value needed for large files... no
checking type of array argument to getgroups... gid_t
checking for size_t... yes
checking for getgroups... yes
checking for working getgroups... yes
checking whether lstat correctly handles trailing slash... yes
checking whether sys/types.h defines makedev... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for getpagesize... yes
checking for working mmap... yes
checking for alarm... yes
checking for dup2... yes
checking for ftruncate... yes
checking for localtime_r... yes
checking for mempcpy... yes
checking for mkdir... yes
checking for munmap... yes
checking for nl_langinfo... yes
checking for rmdir... yes
checking for setlocale... yes
checking for socket... yes
checking for stpcpy... yes
checking for uname... yes
checking for library containing clock_gettime... -lrt
checking for cos in -lm... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gobject-introspection... no
checking for BLKID... yes
checking whether unshare is declared... yes
checking for gperf... /root/esos/work/image/usr/bin/gperf
checking for gtk-doc... no
configure: WARNING:
  You will not be able to create source packages with 'make dist'
  because gtk-doc >= 1.18 is not found.
checking for gtkdoc-check... no
checking for gtkdoc-check... no
checking for gtkdoc-rebase... no
checking for gtkdoc-mkpdf... no
checking whether to build gtk-doc documentation... no
checking for GTKDOC_DEPS... no
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'
make: *** [eudev] Error 1

**Comment by msmith626** [comment]
--snip--
configure.ac:14: require Automake 1.13, but have 1.11.3
autoreconf: automake failed with exit status: 1
--snip--

Try upgrading your automake package. Looks like I need to add 'set -e' to
all of the shell statements so we can catch those errors...

**Comment by dswartz** [comment]
No can do.  This is ubuntu 12.04 and that automake is the latest and greatest for that distro.  Let me try upgrading the VM to 14.x and see...

**Comment by dswartz** [comment]
Okay, that worked!  You probably should replace ubuntu 12.04 with 14.04 or somesuch in the build documentation.  I'm doing a full build (including zfs) now...

**Comment by dswartz** [comment]
Gets much farther now, but now failing trying to build opensm.

osm_console.o: In function `poll':
/usr/include/bits/poll2.h:41: undefined reference to `__poll_chk'
collect2: error: ld returned 1 exit status
make[4]: *** [opensm] Error 1
make[4]: Leaving directory `/root/esos/work/build/opensm-3.3.15/opensm'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/root/esos/work/build/opensm-3.3.15/opensm'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/esos/work/build/opensm-3.3.15'
make[1]: *** [opensm] Error 2
make[1]: Leaving directory `/root/esos'
make: *** [all] Error 2

**Comment by dswartz** [comment]
Unfortunately, '-i' has the side effect of hiding other build issues.  I will need to run this again after the complete build (assuming it works) and look for any other failing components...

**Comment by dswartz** [comment]
Let me come this from a different angle: esos doesn't seem to build with zfs support by default.  I've been doing a 'git checkout master', running the configure script with enable_zfs set to true, and then building.  Unfortunately, this exposes me to bleeding edge injuries.  Is there any way I can build against a stable code base with zfs enabled?

**Comment by msmith626** [comment]
No, not yet. But eventually the "master" branch will be a new stable
branch, but the real "master" branch will always be
development/unstable/bleeding edge. Not much has changed in the way of
packages, especially the ones you're having trouble with. Maybe role back
to a different build system?

--Marc

**Comment by dswartz** [comment]
I'm confused.  How is my build system related to the poll compile error?  I thought this stuff all got built in a sandbox?  Rolling back is problematic, because as we saw earlier, 12.04 fails due to too-old version of automake.  I think for now, I'm going to punt and stick with non-zfs storage (or find some other way of exporting zfs via scst).  Even if I can get this to build, this is a production (soho/lab) setup, so bleeding edge is not something I want to play with...

**Comment by msmith626** [comment]
No, in order to build in a sandbox we'd have to chroot, and then have all
binaries pre-built (or a 2 step build process that builds everything need
to build the real binaries like the compiler, etc.). We catch most of it,
but many projects don't rely on common environment variables and may
projects hard-code paths in (like /usr/include and /usr/lib etc.). We do
the best we can, but its certainly not perfect (not yet anyways). One day
we make look at a different build process, but for now this is what it is.
Just like any other software build, the build can vary between
systems/configurations/software/etc.

Let me know when ZFS is at a stable point/release you want and we'll update
master and I'll build a package for you.


--Marc

**Comment by dswartz** [comment]
Okay, thanks.  Don't get me wrong, I appreciate how much work you put into this project, but without a canonical buildbot 'distro', it's very hard for anyone other than you to get builds to work reliably (If for no other reason than you know how everything hangs together...)  The recent breakage with automake is an example.  Again, please don't take this as criticism/bitching - that is not my intent...

**Comment by msmith626** [comment]
No offense taken, but I do have this: That package eudev wouldn't build on
your system by itself either since it requires a more recent version of
automake. Point is ESOS is just made up of a bunch of other projects.

Marc

**Comment by dswartz** [comment]
On 2015-09-11 12:02, Marc A. Smith wrote:
> No offense taken, but I do have this: That package eudev wouldn't
> build on
>  your system by itself either since it requires a more recent version
> of
>  automake. Point is ESOS is just made up of a bunch of other projects.

Got it.

**Comment by dswartz** [comment]
It did in fact build for me after the eudev thing got resolved.  I'll boot that tonight.  I'm wondering: you build production and debug flavors that are bootable in grub.  Is there any reason the production version couldn't be zfs-aware?  Of course, you would have zfs binaries that couldn't be used, since that kernel wouldn't have usable zfs/spl drivers, but... ?

**Comment by msmith626** [comment]
I don't follow... Elaborate! :)
