### ISSUE TITLE
EU Mirror

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#150]
Hi, it's possible to create EU mirror? I can provide server with good connectivity.

**Comment by msmith626** [comment]
Hi Kristian,

It should certainly be possible and a great addition, but give me a few to
think about this... its only a little complex in the way we track downloads
with the PHP scripts. Thank you for your contributions.


--Marc

**Comment by feldsam** [comment]
Hi, I can help with scripts, I am PHP developer.

**Comment by msmith626** [comment]
Okay, so how would we do this. The server I use here state-side is an
OpenBSD host... do we setup rsync between this server and yours? The PHP
scripts simply log a download count to a DB with relevant information. And
actually, it also will block download of the package files if a user has
downloaded too many (max is 10 per day currently I believe).

Let me know what you think is the best approach.


--Marc

**Comment by feldsam** [comment]
Hi, ok, we can rsync files. Download counts I can store locally and at regular base sync with your DB. I can limit max connections and download speed directly by nginx.

**Comment by feldsam** [comment]
What about this?

**Comment by feldsam** [comment]
Hi, any news?

**Comment by msmith626** [comment]
We've decided not to take action on this. We are entering an agreement with a new provider which will provide better access for most all regions. I do appreciate your willingness though, thank you.
