### ISSUE TITLE
zfs 0.6.5 has been released

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#151]
spl.0.6.5 and zfs.0.6.5 are now available.  I am rebuilding with those to test...

**Comment by dswartz** [comment]
Success!

**Comment by dswartz** [comment]
After migrating all of the VMs to the new zpool and scrubbing it:

[root@esos ~]# zpool status
  pool: tank
 state: ONLINE
  scan: scrub repaired 0 in 0h17m with 0 errors on Sat Sep 12 19:14:32 2015
config:

        NAME                        STATE     READ WRITE CKSUM
        tank                        ONLINE       0     0     0
          mirror-0                  ONLINE       0     0     0
            wwn-0x5000c500412ee41f  ONLINE       0     0     0
            wwn-0x5000c500412ef8b3  ONLINE       0     0     0
          mirror-1                  ONLINE       0     0     0
            wwn-0x5000c50041ab0c47  ONLINE       0     0     0
            wwn-0x5000c50041bd3e87  ONLINE       0     0     0
          mirror-2                  ONLINE       0     0     0
            wwn-0x5000c50041bd703f  ONLINE       0     0     0
            wwn-0x5000c5005621857b  ONLINE       0     0     0
          mirror-3                  ONLINE       0     0     0
            wwn-0x5000c500575759fb  ONLINE       0     0     0
            wwn-0x5000c500575e15b7  ONLINE       0     0     0

errors: No known data errors

**Comment by dswartz** [comment]
And:

NAME          PROPERTY       VALUE  SOURCE
tank/vsphere  compressratio  1.97x  -

Almost 50% space savings...

**Comment by msmith626** [comment]
Great to hear! So we're good updating to 0.6.5 -- those are both the latest
stable releases?

--Marc

**Comment by dswartz** [comment]
Correct.

**Comment by micbis** [comment]
In case you are interest in a pull request for 0.6.5.1, let me know:
https://github.com/byteworks-ch/esos/commit/4ec71647022588f986f188f34390d84d6ec5bd62

**Comment by msmith626** [comment]
Planned on getting to this one today, but thank you.

--Marc

**Comment by msmith626** [comment]
Thanks Michael.
