### ISSUE TITLE
Please add check_zpools.sh for zfs/nagios support

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#157]
https://exchange.nagios.org/directory/Plugins/Operating-Systems/Solaris/check_zpools-2Esh/details

p.s. I'd just as soon strip the trailing '.sh' from the name, but up to you...

**Comment by msmith626** [comment]
I'm on the fence about this... I don't really want to make a whole new
package for it, so maybe I could include it with the Nagios tarball? Or
maybe just stick it in the ESOS Git tree -- maybe under the misc/
directory... let me think about it for a few.

--Marc

**Comment by dswartz** [comment]
I have no problem with how you implement this.  One could argue it *should* be in the stock nagios tarball anyway :)

**Comment by msmith626** [comment]
Okay, I know where I'm going to put it in the source tree. Where does this
file install to on ESOS? I don't see a "nagios" directory anywhere... looks
like maybe just /usr/libexec?

**Comment by msmith626** [comment]
This is completed and committed (7f9a467a5cb2b6bc22385fcd1fb77809d80062d0); let me know if there are any problems. For reference, I created a new "contrib" directory in the source to store third-party things like this and we just pull the file into the archive in the "image" recipe.

--Marc

**Comment by dswartz** [comment]
I'll give that a shot too.
