### ISSUE TITLE
health_check.sh ram threshold should be more adaptive

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#158]
The default is 90%.  If you have a host with a lot of RAM, you end up wasting a lot of it if you don't want to be nagged constantly.  I am about to acquire an off-lease dell R905 with 128GB RAM, and I will need to leave about 13GB unused by ZFS to avoid being bitched at.  Maybe a sliding threshold, depending on how much there is?

**Comment by msmith626** [comment]
Yeah... a while back we made a change to make this nice for vdisk_fileio users so we didn't count the number from the Linux page cache (allocated) so it fixed the warnings for them. This check is really just for show... I added it originally as a filler in that health script, but I'm not sure how useful it is. I don't want it to be an annoyance either.

I'm open to ideas -- I think a percentage always makes sense, but maybe not? How else could we do it?


--Marc

**Comment by dswartz** [comment]
A percentage seems reasonable, but maybe reduce it as RAM increases?  Or pick some magic, minimal amount of RAM to keep available for everything else, and do a min() of that and 10%?  Or something like that?

**Comment by msmith626** [comment]
I think I'm just going to make this some high percentage for now... honestly, like you said, it can be normal for some process to consume just about all of the memory. Maybe make it 98% or 99%? On your normal running ZFS system, what percent is consumed?

**Comment by dswartz** [comment]
On 2015-11-18 10:27, Marc A. Smith wrote:
> I think I'm just going to make this some high percentage for now...
> honestly, like you said, it can be normal for some process to consume
> just about all of the memory. Maybe make it 98% or 99%? On your normal
> running ZFS system, what percent is consumed?

My working set appears to be pretty much as much of the 128GB I give 
it...  The problem with a fixed high percentage is that someone with 8GB 
will only have a couple hundred MB free, which could be problematic, 
whereas big-ram systems would do okay.  Seems to me like we're just 
erring in the other direction, no?  In general, non-block storage ram 
use shouldn't get much above 1GB anyway?  I would vote for a reasonable 
fixed amount (or have a config setting which way to do it), but up to 
you...

**Comment by msmith626** [comment]
Good point, I like that idea. I'll work on this today. And to answer your
question, yes, other systems that don't use ZFS or the Linux page cache
consume very little physical RAM -- basically just for the tmpfs file
systems and that's it.

--Marc

**Comment by msmith626** [comment]
Okay, here is what I'd like to do (feedback please):
- Have a percentage threshold value, and a threshold value in say megabytes.
- Calculate the percentage value from physical RAM to get value in megabytes.
- Then compare these two values in megabytes, and if the amount of available RAM is less than the smallest of these values, trigger a memory-warning message.

That way for systems like yours where a small percentage of memory may be gigabytes, the warning won't trigger.

Question for you: What should the minimum # in megabytes be?

**Comment by msmith626** [comment]
Okay, would you mind trying this script on your system (just SCP to /root and chmod +x and run it there). Hopefully this should do the trick and not produce an alarm on your system... let me know.

(FYI: I had to put .txt extension to get GH to take this.)
[health_chk.sh.txt](https://github.com/astersmith/esos/files/40211/health_chk.sh.txt)

--Marc

**Comment by dswartz** [comment]
On 2015-11-20 10:38, Marc A. Smith wrote:
> Okay, would you mind trying this script on your system (just SCP to
> /root and chmod +x and run it there). Hopefully this should do the
> trick and not produce an alarm on your system... let me know.
> 
> (FYI: I had to put .txt extension to get GH to take this.)
>  health_chk.sh.txt [1]

I'll give it a shot later tonight...

**Comment by msmith626** [comment]
Needed to test some other things so I went ahead and pushed this change...
if its broken, then we'll just fix/tweak it (master).

--Marc

**Comment by dswartz** [comment]
On 2015-11-25 10:17, Marc A. Smith wrote:
> Needed to test some other things so I went ahead and pushed this
> change...
>  if its broken, then we'll just fix/tweak it (master).

sorry i got totally swamped.  i'll take a look at this today and let you 
know...

**Comment by dswartz** [comment]
On 2015-11-20 10:38, Marc A. Smith wrote:
> Okay, would you mind trying this script on your system (just SCP to
> /root and chmod +x and run it there). Hopefully this should do the
> trick and not produce an alarm on your system... let me know.
> 
> (FYI: I had to put .txt extension to get GH to take this.)
>  health_chk.sh.txt [1]

seems to work just fine!

**Comment by msmith626** [comment]
Good deal, thanks.
