### ISSUE TITLE
health_check.sh ram threshold is not being computed correctly?

### ISSUE THREAD

**Issue by dswartz** [astersmith/esos#160]
So I set my zfs arc max threshold very high (expecting to get warnings.  I did not.)  So I ran the script manually and got this:

Physical RAM check...
Total Memory:           131965504 kB
Used Memory:            123951796 kB
Available Memory:       8013708 kB
Memory used percent:    0.9

Looking at the script:

echo "Physical RAM check..."
echo -e "Total Memory:\t\t${mem_total} kB\nUsed Memory:\t\t${mem_used} kB\nAvailable Memory:\t${mem_avail} kB"
prct_mem_used=`echo "${mem_used} ${mem_total}" | awk '{ printf("%.1g", $1 / $2) }'`
echo -e "Memory used percent:\t${prct_mem_used}"

The actual fraction is 0.93, but the above truncates to one digit.  So the in use percentage comes out as "0.9", but that is also the threshold, so the check:

if expr ${prct_disk_used} '>' ${DISK_PRCT_THRESH}

never fires?

**Comment by msmith626** [comment]
So, should we make it so that value isn't truncated?

--Marc

**Comment by dswartz** [comment]
I guess?  Honestly, I just commented it out for the time.  Wasn't sure how the code was supposed to work and just wanted it to shut up :)

**Comment by msmith626** [comment]
FYI: I switched using "expr" to Perl so the comparison of floating point numbers (well, > 1 digit after decimal) now is calculated correctly. This will be in next commit.
