### ISSUE TITLE
eno* network interfaces support

### ISSUE THREAD

**Issue by Prividen** [astersmith/esos#161]
Latest ESOS (esos-master_612615c_dgv) does not recognized "eno*" network interfaces name (Intel Corporation I350 Gigabit Network Connection (rev 01)).
I had to patch /etc/rc.d/rc.network:
if (($iface =~ /enp\d+s\d+/) || ($iface =~ /eno\d+/) || ($iface =~ /eth\d+/) || ($iface =~ /ib\d+/) || ($iface =~ /bond\d+/)) {

and so on...

**Comment by msmith626** [comment]
Hi,

Sorry -- I've actually had this fixed on a local feature branch for a couple months now... I just took those commits into master and did a push. The Buildbot should have a new image posted in about an hour.

--Marc

**Comment by Prividen** [comment]
Ok, thanks!

**Comment by msmith626** [comment]
This image is available and I just tested with a desktop PC and interface 'eno1' is recognized now.

--Marc
