### ISSUE TITLE
Feature request: munin-node

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#167]
Hi, I use munin for gathering information about running systems, will be perfect if esos include munin-node daemon.

Thank you.

**Comment by msmith626** [comment]
Hi,

Yes, I can add this in... give me a day or two (still have a few days of holiday break left). Is there any specific version/branch? I haven't looked at that software to see what the download options are yet...


--Marc

**Comment by feldsam** [comment]
Hi Marc, latest release 2.0.25 should be ok.

**Comment by msmith626** [comment]
I haven't forgotten about this... its written in Perl, which is annoying.
Its got a few Perl module dependencies, so I'm working through those.

--Marc

**Comment by feldsam** [comment]
Hi, what about this? Munin-node will be great for monitoring, it;s widely used tool. Thanks.

**Comment by msmith626** [comment]
Its a decent amount of work as it uses Perl, so we need to install the
required third-party modules to support this. I don't see the door being
knocked down for this feature yet, so I've been putting it off. =)

ESOS already sports the Nagios plugin(s) -- is there any way to use the
Nagios plugin with munin?


--Marc

**Comment by michalkolar** [comment]
+1

**Comment by msmith626** [comment]
Would this re-write in C be acceptable:
https://github.com/munin-monitoring/munin-c

Would this provide the plugins/helpers that are needed?


--Marc

**Comment by feldsam** [comment]
Hi Marc, it should be compatible, better that nothing :) Add please, I can test this week.

**Comment by msmith626** [comment]
This is feature is complete and merged (69f6ac4de479bb68c38671783d750cf495da70e7).
