### ISSUE TITLE
Feature request: LSI Media errors

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#168]
Hi, health_check.sh script should also check for Media errors, I experienced issue with SSD disks in RAID10. Volume was in OPTIMAL state, but disks reports Media Errors. After few months, controller mark one disk as failed and use hotspare, but volume cannot be rebuild without errors, so I have corrupted files on filesystem. Disks should be immediately replaced after any Media errors occur.

**Comment by msmith626** [comment]
Yes, this sounds reasonable. Haven't looked yet, but is that data field in the output of something like '-pdlist' with MegaCLI?

--Marc

**Comment by feldsam** [comment]
Hi, I find media errors by this command

    MegaCli64 -LDPDInfo -aAll |grep 'Media Error'

**Comment by feldsam** [comment]
Article about media errors http://www.theprojectbot.com/what-is-a-punctured-raid-array/

**Comment by msmith626** [comment]
It appears the "Media Error Count" field is also present in the '-pdlist'
command. Since we already capture output of this command in health_chk.sh I
will add a check to see if this value is anything but 0 and will produce a
warning.

--Marc

**Comment by msmith626** [comment]
[health_chk.sh.txt](https://github.com/astersmith/esos/files/81264/health_chk.sh.txt)

Try with the attached script -- if it looks good I'll commit this.


--Marc

**Comment by feldsam** [comment]
Hi, great, it's working

	...
	Checking physical drives...
	** Warning! It appears a MegaRAID physical drive  on adapter 1 contains media errors!
	** Physical media error count: 2
	** Warning! It appears a MegaRAID physical drive  on adapter 1 contains media errors!
	** Physical media error count: 6
	Checked 6 physical drive(s).
	...

**Comment by msmith626** [comment]
Okay, thanks; I have this committed on my machine and fixed that line and a
couple others that produced unneeded white space. I'm working on munin-node
and then will push all of these.

--Marc

**Comment by msmith626** [comment]
This has been committed.
