### ISSUE TITLE
Pacemaker switch DRBD to Primary also if incosistent

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#169]
Hi,
 when drbd is resyncing and one node is in inconsistent state, pacemaker switch ms_drbd from Slave to Master. I don't know, why this is allowed in drbd to switch incosistent node to primary, or why drbd resource doesnt check for state. This behavior is after some update... at the start of using esos pacemaker waits until node is consistent.

**Comment by msmith626** [comment]
Can you replicate this behavior? If so, it'd probably be worthwhile to turn
the cluster debug flag on, so we can get additional information from the
DRBD RA (goes to /var/log/local2.log).

--Marc

**Comment by feldsam** [comment]
Probably my faul. I toke node online without check for drbd status after maintanace. I know, that if node was shoted down by pacemaker, crm rule is created to prevent drbd primary state without admin action.....
