### ISSUE TITLE
Missing ctfw firmware

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#170]
Hello, friend of mine tested ESOS with Qlogic 10G adapters and he found this bug

	[  139.248891] QLogic BR-series 10G Ethernet driver - version: 3.2.25.1
	[  139.248924] bnad_pci_probe : (0xffff88041ea8b000, 0xffffffffa01ad610) PCI Func : (2)
	[  139.248949] bna 0000:03:00.2: Direct firmware load for ctfw-3.2.5.1.bin failed with error -2
	[  139.248952] Can't locate firmware ctfw-3.2.5.1.bin
	[  139.248954] Failed to load Firmware Image!
	[  139.248966] bnad_pci_probe : (0xffff88041ea8c000, 0xffffffffa01ad610) PCI Func : (3)
	[  139.248980] bna 0000:03:00.3: Direct firmware load for ctfw-3.2.5.1.bin failed with error -2
	[  139.248982] Can't locate firmware ctfw-3.2.5.1.bin
	[  139.248983] Failed to load Firmware Image!

He need to manulay add that firmware file because is missing

**Comment by msmith626** [comment]
Ah, I assume that he is using the "master" branch of ESOS. The ctfw-*.bin
firmware exists in the image, just an older version. Sounds like the
linux-firmware package needs to be updated. I will be up'ing the kernel
again in master and when I do this I'll update linux-firmware as well.

--Marc

**Comment by msmith626** [comment]
This has been committed and the new package (master branch) has posted. I verified the 'ctfw-3.2.5.1.bin' blob is included in the new version of linux-firmware.

--Marc
