### ISSUE TITLE
QLogic BR-1860 Support

### ISSUE THREAD

**Issue by trkince** [astersmith/esos#173]
Hello,
Is ESOS supporting QLogic BR-1860 16G FC?
Best Regards.

**Comment by msmith626** [comment]
I would say no, not at this time. I believe that is one of the adapters
imported from Brocade, and probably not supported by the qla2xxx driver in
SCST.

If your intention is to do 16 Gb FC, I'd recommend the the QLogic 2600
series. I have been using some QLE2672-CK adapters in production for a
while now and they work great.


--Marc

**Comment by trkince** [comment]
Thanks.
