### ISSUE TITLE
Zabbix Agent

### ISSUE THREAD

**Issue by eliesertopassi** [astersmith/esos#174]
Hi,

It's possible to run Zabbix 2.4 or 3.0 agent on ESOS ?
I'm trying to get processor, memory and interfaces info from snmp, but it's not working properly... and I prefer get those info from Zabbix Agent.

**Comment by msmith626** [comment]
I've never heard of Zabbix... Is there just a simple agent that can be
installed (daemon)? In this like Munin? There is another request for that
one too... I assume these are all Nagios knock-offs?

--Marc

**Comment by eliesertopassi** [comment]
Yes. It’s like nagios / cacti.

 

On CentOS 5/6/7 I just do “yum install zabbix-agent” and set couple options in a config file.

 

I’ve tried to install it on ESOS using the rpm packages but there is a lot of dependecies.

 

 

 


 <https://webmail.grupowdg.com.br/#1> 

Elieser Carlos Topassi / Especialista em Infraestrutura 

Grupo WDG 
+55 17 3353 9173 Ramal 1701 
Avenida Gabriel Jorge Cury, 232 São José do Rio Preto, São Paulo 

 <https://htmlsig.com/t/0000001BSQ0D4>  <https://htmlsig.com/t/0000001BS7XRC>  <https://htmlsig.com/t/0000001BN73ZR> 

	
	
	

 

 

De: Marc A. Smith [mailto:notifications@github.com] 
Enviada em: terça-feira, 26 de abril de 2016 09:33
Para: astersmith/esos <esos@noreply.github.com>
Cc: eliesertopassi <elieser.topassi@grupowdg.com.br>; Author <author@noreply.github.com>
Assunto: Re: [astersmith/esos] Zabbix Agent (#174)

 

I've never heard of Zabbix... Is there just a simple agent that can be
installed (daemon)? In this like Munin? There is another request for that
one too... I assume these are all Nagios knock-offs?

--Marc

**Comment by msmith626** [comment]
Which branch/version? It appears there are several choices...

**Comment by feldsam** [comment]
Hi, what about munin? :)

**Comment by msmith626** [comment]
Haha, yeah, I haven't forgot about it.

My work-load has reduced significantly, so I'll commit to adding munin-node
and then Zabbix this week. And yes, for real, I'll do it this time -- you
have been patiently waiting. =)


--Marc

**Comment by eliesertopassi** [comment]
Hi Marc,

Last night, I'd manually installed all requisites for Zabbix Agent (I've used the CentOS 5.11 x64 rpm packages) and now it is working propertly.

Thanks for all.
