### ISSUE TITLE
Few problems after install latest master

### ISSUE THREAD

**Issue by feldsam** [astersmith/esos#176]
First one

> [root@storage2 ~]# crm_mon
Defaulting to one-shot mode
You need to have curses available at compile time to enable console mode

Next one

> [root@storage2 ~]# cat /sys/block/sda/queue/scheduler 
none

So I cant set i/o scheduler and related settings like this

>echo  deadline > /sys/block/sda/queue/scheduler
echo 0 > /sys/block/sda/queue/iosched/front_merges
echo 150 > /sys/block/sda/queue/iosched/read_expire
echo 1500 > /sys/block/sda/queue/iosched/write_expire

Personally I don't like new two rows menu in TUI and you also removed backend storage information like "MegaRaid adapter info and related", also navigation is worse, because I can't use left/right arrows to move in menu.

My personal experience with kernel 4.4.4+ is bad. I installed it on compute nodes and I got i/o errors, I also try newer 4.5 version, but without success, so I can't trust it. I stick with 4.1.11 (esos-master_4a32709)

btw, I just upgraded from older Nov 2015 release to 21 Apr 2016 (esos-master_4a32709) and I see "copy_manager_sess" in sessions, what is it? (8 LUNs, 0 Cmds, 32 Read, 0 Write)

**Comment by feldsam** [comment]
I see, new target copy_manager_tgt disable state, can I delete it?

**Comment by msmith626** [comment]
On Fri, May 13, 2016 at 3:11 PM, Kristian Feldsam <notifications@github.com>
wrote:

> First one
>
> [root@storage2 ~]# crm_mon
> Defaulting to one-shot mode
> You need to have curses available at compile time to enable console mode
>
>
Moving to ncurses wide-character support is probably the culprit behind
this one... I'll investigate.


> Next one
>
> [root@storage2 ~]# cat /sys/block/sda/queue/scheduler
> none
>
> So I cant set i/o scheduler and related settings like this
>
> echo deadline > /sys/block/sda/queue/scheduler
> echo 0 > /sys/block/sda/queue/iosched/front_merges
> echo 150 > /sys/block/sda/queue/iosched/read_expire
> echo 1500 > /sys/block/sda/queue/iosched/write_expire
>
>
Yes, we now enable the blk-mq replacement stack by default so, no more IO
scheduler as we know it.


> Personally I don't like new two rows menu in TUI and you also removed
> backend storage information like "MegaRaid adapter info and related", also
> navigation is worse, because I can't use left/right arrows to move in menu.
>

Yeah, its gonna be different... not sure of another way with CDK to expand
menus. I'm open to ideas if you have any...

I'm working on the new multi-vendor RAID CLI tool and that will replace
MegaRAID-only functionality. I can replace the old functions for now though.



> My personal experience with kernel 4.4.4+ is bad. I installed it on
> compute nodes and I got i/o errors, I also try newer 4.5 version, but
> without success, so I can't trust it. I stick with 4.1.11
> (esos-master_4a32709)
>

Okay, 4.5 is current stable. I'll test too and update as needed.



> btw, I just upgraded from older Nov 2015 release to 21 Apr 2016
> (esos-master_4a32709) and I see "copy_manager_sess" in sessions, what is
> it? (8 LUNs, 0 Cmds, 32 Read, 0 Write)
>

Its a feature in SCST -- the TUI should now hide this, its safe to ignore.

**Comment by msmith626** [comment]
The crm_mon curses issue should be fixed and I enabled the add/remove MegaRAID volume under the HW RAID menu for now. Both are in 1926c9f.

--Marc
