### ISSUE TITLE
Add SAS Target Driver Support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [astersmith/esos#24]
```
Request to add support for SAS targets to ESOS by enabling the 'mvsas_tgt' and 
'mpt' SCST target drivers (Marvell SAS and LSI/MPT adapters). Original request 
from "dpenner2010@gmail.com" on June 28th, 2013.
```

Original issue reported on code.google.com by `msmith...@gmail.com` on 25 Jul 2013 at 6:47

**Comment by msmith626** [comment]
We've decided not to take action on this. This is the only request for SAS front-end target support, and after reviewing the SAS target implementation in SCST, it appears to still be relatively untested. This may change in the future, but closing the issue for now.

--Marc
