### ISSUE TITLE
Add DM Multipath Support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [astersmith/esos#88]
```
Request to add Linux DM multipath support in ESOS. Enabling the kernel option 
is straightforward, but the multipath-tools package 
(http://christophe.varoqui.free.fr/) is a requirement. The multipath-tools 
package relies on udev, and currently ESOS utilizies mdev (instead of udev).

When/if ESOS moves to udev, adding DM multipath will be an option.


--Marc
```

Original issue reported on code.google.com by `msmith...@gmail.com` on 20 Oct 2014 at 2:04

**Comment by msmith626** [comment]
I've merged in udev support to master, and will work on adding the multipath-tools package in the next few days.

--Marc

**Comment by msmith626** [comment]
The multipath-tools package has been added, and the DM multipath kernel option enabled. I have yet to test this personally, but I expect it to function as expected.

--Marc
