### ISSUE TITLE
Feature requests add elevator noop at tui

### ISSUE THREAD

**Issue by GoogleCodeExporter** [astersmith/esos#95]
```
Please add elevator noop at tui.

```

Original issue reported on code.google.com by `javier.l...@gmail.com` on 22 Mar 2015 at 2:00

**Comment by dswartz** [comment]
Note also that if you are using ZFS, it wants the noop algorithm (IIRC.)

**Comment by msmith626** [comment]
At this time, in the future stable/release branch of ESOS, we now use blk-mq by default, so there currently isn't a scheduler to choose.

Will revisit if this comes up in the future.

--Marc
