### ISSUE TITLE
Latest revision 770 doest't work correctly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [astersmith/esos#97]
```
Boot log:

Fri Mar 27 11:17:31 2015: Updating module dependencies...
Fri Mar 27 11:17:31 2015: depmod: chdir(lib/modules/3.14.36-esos.prod): No such 
file or directory

Fri Mar 27 11:17:31 2015: Loading the Linux Ethernet Bonding driver...
Fri Mar 27 11:17:31 2015: modprobe: chdir(3.14.36-esos.prod): No such file or 
directory

Fri Mar 27 11:17:32 2015: ERROR: Can't open /sys/class/net/bonding_masters: 
Permission denied at /etc/rc.d/rc.network line 92.

Fri Mar 27 11:17:45 2015: Loading the QLogic Fibre Channel HBA module...
Fri Mar 27 11:17:45 2015: modprobe: chdir(3.14.36-esos.prod): No such file or 
directory

Fri Mar 27 11:17:50 2015: Loading btier devices...
Fri Mar 27 11:17:50 2015: modprobe: chdir(3.14.36-esos.prod): No such file or 
directory
```

Original issue reported on code.google.com by `i...@feldsam.cz` on 27 Mar 2015 at 11:23

**Comment by feldsam** [comment]
Hi,

ok, I understand that mounting by label is important. So simple concept:

On ESOS boot time check by command blkid for duplicate labels and by command eject remove all devices which are not same as boot device.

ex.


booting from /dev/sdc

blkid result

/dev/sdd4: LABEL="esos_logs" UUID="7986817e-a6db-44e8-aec9-56619cbd19aa"
/dev/sdd3: LABEL="esos_conf" UUID="69aa64c9-f8cf-490d-a981-e8da2688b4c6"
/dev/sdd2: LABEL="esos_root" UUID="a43b31e1-1853-49ec-9ad6-af57387e78e0"
/dev/sdd1: LABEL="esos_boot" UUID="da180bee-d0de-4a67-b333-1648cc99b515"
/dev/sdc4: LABEL="esos_logs" UUID="6a3cefc4-50c6-4fc8-bf41-4ef00fe6bc0a"
/dev/sdc3: LABEL="esos_conf" UUID="a92cd73e-2af8-41f6-b316-81de10d78297"
/dev/sdc2: LABEL="esos_root" UUID="f4695fa9-8d1f-43fd-87e0-973f0b31f29b"
/dev/sdc1: LABEL="esos_boot" UUID="68de86d4-1674-4bbc-8b51-d7dda7974fb5"


Found one duplicate device /dev/sdd

remove it

eject /dev/sdd



When you want install update, just "close tray"

eject -t /dev/sdd and device will be available for installation.

**Comment by msmith626** [comment]
Nice find! Glad you were able to find a simple solution to meet your requirements.

--Marc

**Comment by msmith626** [comment]
Nice find! Glad you were able to find a simple solution to meet your requirements.

--Marc

**Comment by msmith626** [comment]
Nice find! Glad you were able to find a simple solution to meet your requirements.

--Marc

**Comment by msmith626** [comment]
Nice find! Glad you were able to find a simple solution to meet your requirements.

--Marc

**Comment by msmith626** [comment]
Nice find! Glad you were able to find a simple solution to meet your requirements.

--Marc

**Comment by msmith626** [comment]
Nice find! Glad you were able to find a simple solution to meet your requirements.

--Marc

**Comment by msmith626** [comment]
Nice find! Glad you were able to find a simple solution to meet your requirements.

--Marc
